import {
  AcademicResource,
  Subject,
  StudyGroup,
  Faculty,
  FacultyReview,
  AcademicEvent,
  WikiArticle,
  AcademicRequest,
} from "@/types/academic.types";

// ─── Seed Subjects ───────────────────────────────────────────────────────────

export const SEED_SUBJECTS: Subject[] = [
  // ── CSE Subjects ──
  {
    code: "CS501PC",
    name: "Database Management Systems",
    departmentId: "cse",
    semester: 5,
    credits: 4,
    description: "Concepts of Relational Database Design, SQL, Normalization, Indexing, and Transaction Processing (ACID).",
    syllabusSummary: "Unit I: Intro to DBMS, ER Model. Unit II: Relational Algebra & SQL. Unit III: Schema Refinement & Normal Forms (1NF-BCNF). Unit IV: Transaction Management & Concurrency Control. Unit V: Storage and Indexing (B+ Trees, Hashing).",
    totalResourcesCount: 4,
    facultyInCharge: ["Dr. K. Srinivas Rao", "Prof. P. Lakshmi"],
  },
  {
    code: "CS502PC",
    name: "Operating Systems",
    departmentId: "cse",
    semester: 5,
    credits: 3,
    description: "Process Management, Threads, CPU Scheduling, Deadlocks, Memory Management, and File Systems.",
    syllabusSummary: "Unit I: Operating System Structure & System Calls. Unit II: Process Scheduling & Synchronization. Unit III: Deadlock Avoidance and Prevention. Unit IV: Virtual Memory & Page Replacement Algorithms. Unit V: Mass-Storage Structure & File System Implementation.",
    totalResourcesCount: 3,
    facultyInCharge: ["Dr. M. Ramanathan"],
  },
  {
    code: "CS503PC",
    name: "Design and Analysis of Algorithms",
    departmentId: "cse",
    semester: 5,
    credits: 4,
    description: "Algorithm complexity analysis, Divide & Conquer, Greedy method, Dynamic Programming, Backtracking, and Branch & Bound.",
    syllabusSummary: "Unit I: Asymptotic Notations & Recurrence Relations. Unit II: Divide and Conquer (Merge, Quick Sort). Unit III: Dynamic Programming (0/1 Knapsack, TSP) & Greedy Method. Unit IV: Backtracking (N-Queens, Graph Coloring). Unit V: NP-Hard & NP-Complete Problems.",
    totalResourcesCount: 3,
    facultyInCharge: ["Dr. K. Srinivas Rao"],
  },
  {
    code: "CS601PC",
    name: "Computer Networks",
    departmentId: "cse",
    semester: 6,
    credits: 3,
    description: "OSI and TCP/IP Reference models, Data Link Layer, Network Layer routing algorithms, Transport layer, and Application protocols.",
    syllabusSummary: "Unit I: Network Models, Physical Layer basics. Unit II: Data Link Layer Protocols & Error Detection. Unit III: Network Layer, IP Addressing, Routing Algorithms (Dijkstra, Distance Vector). Unit IV: Transport Layer (TCP, UDP, Congestion Control). Unit V: Application Layer (DNS, HTTP, SMTP).",
    totalResourcesCount: 2,
    facultyInCharge: ["Prof. P. Lakshmi"],
  },
  {
    code: "CS602PC",
    name: "Web Technologies",
    departmentId: "cse",
    semester: 6,
    credits: 3,
    description: "Modern Fullstack web architecture, React, Node.js, RESTful services, and security practices.",
    syllabusSummary: "Unit I: HTML5, CSS3, ES6 JavaScript. Unit II: Node.js, Express framework, Middleware. Unit III: REST APIs & MongoDB/Postgres integration. Unit IV: React Component Architecture, Hooks, State Management. Unit V: Authentication, OAuth, and Cloud Deployment.",
    totalResourcesCount: 2,
    facultyInCharge: ["Dr. K. Srinivas Rao"],
  },
  {
    code: "CS401PC",
    name: "Discrete Mathematics",
    departmentId: "cse",
    semester: 4,
    credits: 3,
    description: "Set theory, Propositional Calculus, Graph Theory, Combinatorics, and Algebraic Structures.",
    syllabusSummary: "Unit I: Mathematical Logic & Predicates. Unit II: Relations, Functions, and Lattices. Unit III: Algebraic Structures & Group Theory. Unit IV: Elementary Combinatorics & Generating Functions. Unit V: Graph Theory & Trees.",
    totalResourcesCount: 1,
  },

  // ── ECE Subjects ──
  {
    code: "EC501PC",
    name: "Microprocessors and Microcontrollers",
    departmentId: "ece",
    semester: 5,
    credits: 4,
    description: "8086 Architecture, Assembly Language Programming, Memory Interfacing, and 8051 Microcontroller applications.",
    syllabusSummary: "Unit I: 8086 Microprocessor Architecture & Pin Diagram. Unit II: 8086 Assembly Language Programming & Addressing Modes. Unit III: Interfacing I/O Devices (8255, 8259, 8251). Unit IV: 8051 Microcontroller Architecture & Instruction Set. Unit V: 8051 Interfacing with LCD, Stepper Motor, ADC/DAC.",
    totalResourcesCount: 3,
    facultyInCharge: ["Dr. V. Sudhakar Reddy"],
  },
  {
    code: "EC502PC",
    name: "Digital Signal Processing",
    departmentId: "ece",
    semester: 5,
    credits: 4,
    description: "Discrete Fourier Transform (DFT), Fast Fourier Transform (FFT), IIR and FIR filter design techniques.",
    syllabusSummary: "Unit I: Discrete-Time Signals & Z-Transforms. Unit II: Discrete Fourier Transform (DFT) and FFT Algorithms (DIT/DIF). Unit III: IIR Filter Design (Butterworth, Chebyshev). Unit IV: FIR Filter Design (Windowing techniques). Unit V: Multirate Digital Signal Processing.",
    totalResourcesCount: 2,
    facultyInCharge: ["Dr. V. Sudhakar Reddy", "Dr. B. Anusha"],
  },
  {
    code: "EC601PC",
    name: "VLSI Design",
    departmentId: "ece",
    semester: 6,
    credits: 3,
    description: "CMOS Logic, Layout design rules, Static & Dynamic CMOS Circuits, Verilog HDL modeling and FPGA implementation.",
    syllabusSummary: "Unit I: Introduction to MOS Transistors & CMOS Fabrication. Unit II: CMOS Inverter DC Characteristics & Switching Properties. Unit III: Layout Design Rules, Stick Diagrams & Euler Path. Unit IV: Static vs Dynamic Logic Circuits. Unit V: Verilog HDL Modeling & FPGA Synthesis.",
    totalResourcesCount: 2,
    facultyInCharge: ["Dr. B. Anusha"],
  },
  {
    code: "EC401PC",
    name: "Signals and Systems",
    departmentId: "ece",
    semester: 4,
    credits: 4,
    description: "Continuous and Discrete time signals, LTI systems, Fourier Series, Fourier Transform, and Laplace Transform.",
    syllabusSummary: "Unit I: Signal Classification & Operations. Unit II: Linear Time-Invariant (LTI) Systems & Convolution. Unit III: Fourier Series Representation of Periodic Signals. Unit IV: Fourier Transform & Properties. Unit V: Laplace Transform & Region of Convergence (ROC).",
    totalResourcesCount: 2,
    facultyInCharge: ["Dr. V. Sudhakar Reddy"],
  },
];

// ─── Seed Academic Resources ─────────────────────────────────────────────────

export const SEED_RESOURCES: AcademicResource[] = [
  // ── CSE Resources ──
  {
    id: "res-cse-001",
    title: "Complete DBMS Handwritten Revision Notes (Units 1-5)",
    description: "Comprehensive handwritten notes covering relational algebra, SQL triggers, 3NF/BCNF normalization, and transaction locking protocols. Ideal for mid-terms and university finals.",
    departmentId: "cse",
    subjectCode: "CS501PC",
    subjectName: "Database Management Systems",
    semester: 5,
    academicYear: "2024-2025",
    resourceType: "NOTE",
    fileUrl: "/mock/docs/dbms_handwritten_complete.pdf",
    fileType: "pdf",
    fileSize: 4200000, // 4.2 MB
    uploaderId: "user-std-101",
    uploaderName: "K. Rohit Reddy",
    uploaderDepartment: "Computer Science & Engineering",
    isVerifiedByCoordinator: true,
    verifiedBy: "user-coord-01",
    verifiedByName: "Dr. K. Srinivas Rao",
    verifiedAt: "2026-08-15T10:30:00Z",
    downloadsCount: 342,
    upvotesCount: 89,
    commentsCount: 12,
    tags: ["Handwritten", "Normalization", "SQL", "Unit 1-5", "Exam Ready"],
    versions: [
      {
        versionNumber: 1,
        fileUrl: "/mock/docs/dbms_handwritten_v1.pdf",
        fileSize: 3900000,
        uploadedBy: "K. Rohit Reddy",
        uploadedAt: "2026-08-10T09:00:00Z",
        changeLog: "Initial upload covering Units 1-4.",
      },
      {
        versionNumber: 2,
        fileUrl: "/mock/docs/dbms_handwritten_complete.pdf",
        fileSize: 4200000,
        uploadedBy: "K. Rohit Reddy",
        uploadedAt: "2026-08-15T10:00:00Z",
        changeLog: "Added Unit 5 Indexing & B+ Trees + sample SQL queries.",
      },
    ],
    createdAt: "2026-08-10T09:00:00Z",
    updatedAt: "2026-08-15T10:00:00Z",
  },
  {
    id: "res-cse-002",
    title: "Previous 5 Years Solved Question Papers (2020-2025) — DBMS",
    description: "Compiled and solved previous year university exam questions with step-by-step solutions for ER-diagrams and BCNF decompositions.",
    departmentId: "cse",
    subjectCode: "CS501PC",
    subjectName: "Database Management Systems",
    semester: 5,
    academicYear: "2024-2025",
    resourceType: "PYQ",
    fileUrl: "/mock/docs/dbms_pyq_solved_5yrs.pdf",
    fileType: "pdf",
    fileSize: 6800000, // 6.8 MB
    uploaderId: "user-std-102",
    uploaderName: "Sneha Varma",
    uploaderDepartment: "Computer Science & Engineering",
    isVerifiedByCoordinator: true,
    verifiedBy: "user-coord-01",
    verifiedByName: "Dr. K. Srinivas Rao",
    verifiedAt: "2026-08-18T14:20:00Z",
    downloadsCount: 512,
    upvotesCount: 145,
    commentsCount: 18,
    tags: ["PYQ", "Solved", "JNTUH/MLRIT", "Exam Prep"],
    createdAt: "2026-08-18T12:00:00Z",
    updatedAt: "2026-08-18T14:20:00Z",
  },
  {
    id: "res-cse-003",
    title: "Operating Systems CPU Scheduling & Deadlock Cheatsheet",
    description: "Quick 4-page formula sheet summarizing SJF, Round Robin, Banker's Algorithm, Page replacement (FIFO, LRU, Optimal), and Disk scheduling algorithms.",
    departmentId: "cse",
    subjectCode: "CS502PC",
    subjectName: "Operating Systems",
    semester: 5,
    academicYear: "2024-2025",
    resourceType: "CHEATSHEET",
    fileUrl: "/mock/docs/os_scheduling_cheatsheet.pdf",
    fileType: "pdf",
    fileSize: 1250000,
    uploaderId: "user-std-103",
    uploaderName: "V. Sai Kumar",
    uploaderDepartment: "Computer Science & Engineering",
    isVerifiedByCoordinator: false,
    downloadsCount: 198,
    upvotesCount: 47,
    commentsCount: 5,
    tags: ["Cheatsheet", "Formulas", "CPU Scheduling", "Deadlock", "Quick Review"],
    createdAt: "2026-08-20T16:45:00Z",
    updatedAt: "2026-08-20T16:45:00Z",
  },
  {
    id: "res-cse-004",
    title: "DAA Complete Lab Manual with C++ & Python Code",
    description: "Official lab manual with verified code solutions for QuickSort, 0/1 Knapsack, Kruskal's, Prim's, TSP, and 8-Queens problem with output screenshots.",
    departmentId: "cse",
    subjectCode: "CS503PC",
    subjectName: "Design and Analysis of Algorithms",
    semester: 5,
    academicYear: "2024-2025",
    resourceType: "LAB_MANUAL",
    fileUrl: "/mock/docs/daa_lab_manual_verified.pdf",
    fileType: "pdf",
    fileSize: 3400000,
    uploaderId: "user-std-104",
    uploaderName: "Ananya Deshmukh",
    uploaderDepartment: "Computer Science & Engineering",
    isVerifiedByCoordinator: true,
    verifiedBy: "user-coord-01",
    verifiedByName: "Dr. K. Srinivas Rao",
    verifiedAt: "2026-08-22T11:15:00Z",
    downloadsCount: 276,
    upvotesCount: 78,
    commentsCount: 9,
    tags: ["Lab Manual", "C++", "Python", "Algorithms", "Verified Code"],
    createdAt: "2026-08-22T08:30:00Z",
    updatedAt: "2026-08-22T11:15:00Z",
  },
  {
    id: "res-cse-005",
    title: "Computer Networks Subnetting & Routing Protocols Guide",
    description: "Detailed guide to IPv4/IPv6 CIDR subnetting calculations, Distance Vector Routing vs Link State Routing, and Wireshark packet capture analysis.",
    departmentId: "cse",
    subjectCode: "CS601PC",
    subjectName: "Computer Networks",
    semester: 6,
    academicYear: "2024-2025",
    resourceType: "NOTE",
    fileUrl: "/mock/docs/cn_subnetting_guide.pdf",
    fileType: "pdf",
    fileSize: 2100000,
    uploaderId: "user-std-101",
    uploaderName: "K. Rohit Reddy",
    uploaderDepartment: "Computer Science & Engineering",
    isVerifiedByCoordinator: false,
    downloadsCount: 145,
    upvotesCount: 36,
    commentsCount: 4,
    tags: ["Networking", "Subnetting", "CIDR", "Wireshark"],
    createdAt: "2026-08-25T14:10:00Z",
    updatedAt: "2026-08-25T14:10:00Z",
  },
  {
    id: "res-cse-006",
    title: "Web Technologies Full Stack Project Boilerplate & Notes",
    description: "Step-by-step tutorial on building JWT-authenticated REST APIs with Express & Prisma ORM, connected to a Next.js frontend with Tailwind CSS.",
    departmentId: "cse",
    subjectCode: "CS602PC",
    subjectName: "Web Technologies",
    semester: 6,
    academicYear: "2024-2025",
    resourceType: "REFERENCE_BOOK",
    fileUrl: "/mock/docs/fullstack_web_guide.pdf",
    fileType: "pdf",
    fileSize: 5200000,
    uploaderId: "user-std-105",
    uploaderName: "Pranav Joshi",
    uploaderDepartment: "Computer Science & Engineering",
    isVerifiedByCoordinator: false,
    downloadsCount: 220,
    upvotesCount: 65,
    commentsCount: 8,
    tags: ["React", "NodeJS", "Fullstack", "REST API", "JWT"],
    createdAt: "2026-08-28T18:00:00Z",
    updatedAt: "2026-08-28T18:00:00Z",
  },

  // ── ECE Resources ──
  {
    id: "res-ece-001",
    title: "8086 Assembly Language Programs & 8051 Interfacing Notes",
    description: "Complete assembly programs for arithmetic operations, string manipulations, and hardware interfacing (8255 PPI, stepper motor, 7-segment display).",
    departmentId: "ece",
    subjectCode: "EC501PC",
    subjectName: "Microprocessors and Microcontrollers",
    semester: 5,
    academicYear: "2024-2025",
    resourceType: "NOTE",
    fileUrl: "/mock/docs/8086_assembly_interfacing.pdf",
    fileType: "pdf",
    fileSize: 3800000,
    uploaderId: "user-std-201",
    uploaderName: "T. Manasa",
    uploaderDepartment: "Electronics & Communication Engineering",
    isVerifiedByCoordinator: true,
    verifiedBy: "user-coord-02",
    verifiedByName: "Dr. V. Sudhakar Reddy",
    verifiedAt: "2026-08-16T12:00:00Z",
    downloadsCount: 289,
    upvotesCount: 74,
    commentsCount: 7,
    tags: ["8086", "8051", "Assembly", "Interfacing", "ECE"],
    createdAt: "2026-08-12T10:00:00Z",
    updatedAt: "2026-08-16T12:00:00Z",
  },
  {
    id: "res-ece-002",
    title: "DSP Fast Fourier Transform (FFT) & Filter Design Problems Solved",
    description: "Step-by-step solved problems on 8-point DIT and DIF FFT, Butterworth and Chebyshev IIR filter calculations, and Bilinear Transformation.",
    departmentId: "ece",
    subjectCode: "EC502PC",
    subjectName: "Digital Signal Processing",
    semester: 5,
    academicYear: "2024-2025",
    resourceType: "NOTE",
    fileUrl: "/mock/docs/dsp_fft_filter_solved.pdf",
    fileType: "pdf",
    fileSize: 4600000,
    uploaderId: "user-std-202",
    uploaderName: "G. Karthik",
    uploaderDepartment: "Electronics & Communication Engineering",
    isVerifiedByCoordinator: true,
    verifiedBy: "user-coord-02",
    verifiedByName: "Dr. V. Sudhakar Reddy",
    verifiedAt: "2026-08-19T15:30:00Z",
    downloadsCount: 310,
    upvotesCount: 92,
    commentsCount: 11,
    tags: ["DSP", "FFT", "IIR Filter", "Chebyshev", "Solved Examples"],
    createdAt: "2026-08-17T11:20:00Z",
    updatedAt: "2026-08-19T15:30:00Z",
  },
  {
    id: "res-ece-003",
    title: "VLSI CMOS Stick Diagrams & Euler Path Solved Assignments",
    description: "Tutorial with colored diagrams explaining how to draw stick diagrams, calculate Euler paths, and design minimum area CMOS layouts for complex logic gates.",
    departmentId: "ece",
    subjectCode: "EC601PC",
    subjectName: "VLSI Design",
    semester: 6,
    academicYear: "2024-2025",
    resourceType: "ASSIGNMENT_SOLUTION",
    fileUrl: "/mock/docs/vlSI_stick_diagrams_guide.pdf",
    fileType: "pdf",
    fileSize: 3100000,
    uploaderId: "user-std-201",
    uploaderName: "T. Manasa",
    uploaderDepartment: "Electronics & Communication Engineering",
    isVerifiedByCoordinator: false,
    downloadsCount: 180,
    upvotesCount: 51,
    commentsCount: 6,
    tags: ["VLSI", "CMOS", "Stick Diagrams", "Euler Path", "Layout"],
    createdAt: "2026-08-24T09:15:00Z",
    updatedAt: "2026-08-24T09:15:00Z",
  },
  {
    id: "res-ece-004",
    title: "Signals and Systems University PYQs (2021-2025)",
    description: "Previous year exam questions on Convolution Integral, Fourier Series expansions, and Laplace ROC properties with complete working solutions.",
    departmentId: "ece",
    subjectCode: "EC401PC",
    subjectName: "Signals and Systems",
    semester: 4,
    academicYear: "2024-2025",
    resourceType: "PYQ",
    fileUrl: "/mock/docs/signals_systems_pyqs.pdf",
    fileType: "pdf",
    fileSize: 5100000,
    uploaderId: "user-std-203",
    uploaderName: "B. Harish",
    uploaderDepartment: "Electronics & Communication Engineering",
    isVerifiedByCoordinator: true,
    verifiedBy: "user-coord-02",
    verifiedByName: "Dr. V. Sudhakar Reddy",
    verifiedAt: "2026-08-26T16:00:00Z",
    downloadsCount: 240,
    upvotesCount: 63,
    commentsCount: 8,
    tags: ["Signals", "Laplace", "Fourier", "PYQ", "Solved"],
    createdAt: "2026-08-25T10:00:00Z",
    updatedAt: "2026-08-26T16:00:00Z",
  },
];

// ─── Seed Faculty ────────────────────────────────────────────────────────────

export const SEED_FACULTY: Faculty[] = [
  // ── CSE Faculty ──
  {
    id: "fac-cse-001",
    name: "Dr. K. Srinivas Rao",
    designation: "Professor & Head of Department",
    departmentId: "cse",
    email: "srinivasrao.k@mlrit.ac.in",
    cabinLocation: "Block A - Room 401 (HOD Cabin)",
    officeHours: "Monday & Wednesday: 2:30 PM - 4:30 PM",
    specialization: ["Distributed Systems", "Database Optimization", "Cloud Computing"],
    subjectsHandled: ["Database Management Systems", "Design and Analysis of Algorithms", "Cloud Architecture"],
    rating: 4.8,
    reviewCount: 38,
    isAcceptingStudents: true,
    bio: "Ph.D. from IIT Madras with over 18 years of academic and research experience. Passionate about scalable database architectures and mentoring student research projects.",
  },
  {
    id: "fac-cse-002",
    name: "Prof. P. Lakshmi",
    designation: "Associate Professor",
    departmentId: "cse",
    email: "lakshmi.p@mlrit.ac.in",
    cabinLocation: "Block A - Room 312",
    officeHours: "Tuesday & Thursday: 10:00 AM - 12:00 PM",
    specialization: ["Computer Networks", "Cybersecurity", "IoT Security Protocols"],
    subjectsHandled: ["Computer Networks", "Information Security", "Operating Systems"],
    rating: 4.6,
    reviewCount: 29,
    isAcceptingStudents: true,
    bio: "Author of 15+ international journal papers in network protocols. Known for highly engaging classroom discussions and practical Wireshark lab sessions.",
  },
  {
    id: "fac-cse-003",
    name: "Dr. M. Ramanathan",
    designation: "Assistant Professor (Sr. Grade)",
    departmentId: "cse",
    email: "ramanathan.m@mlrit.ac.in",
    cabinLocation: "Block A - Room 208",
    officeHours: "Friday: 1:30 PM - 3:30 PM",
    specialization: ["Operating Systems", "Compiler Design", "Kernel Programming"],
    subjectsHandled: ["Operating Systems", "Systems Programming", "Compiler Design"],
    rating: 4.2,
    reviewCount: 21,
    isAcceptingStudents: false,
    bio: "Focuses on Linux kernel internals and low-level virtualization. Strict on project deadlines but provides detailed feedback on code structure.",
  },

  // ── ECE Faculty ──
  {
    id: "fac-ece-001",
    name: "Dr. V. Sudhakar Reddy",
    designation: "Professor & Dean Academics",
    departmentId: "ece",
    email: "sudhakar.v@mlrit.ac.in",
    cabinLocation: "Block B - Room 302",
    officeHours: "Monday, Wednesday: 3:00 PM - 5:00 PM",
    specialization: ["Embedded Systems", "Signal Processing", "Robotics"],
    subjectsHandled: ["Microprocessors and Microcontrollers", "Digital Signal Processing", "Signals and Systems"],
    rating: 4.9,
    reviewCount: 42,
    isAcceptingStudents: true,
    bio: "Senior IEEE Fellow with extensive background in defense signal processing and microcontroller system design.",
  },
  {
    id: "fac-ece-002",
    name: "Dr. B. Anusha",
    designation: "Associate Professor",
    departmentId: "ece",
    email: "anusha.b@mlrit.ac.in",
    cabinLocation: "Block B - Room 215",
    officeHours: "Tuesday & Thursday: 2:00 PM - 4:00 PM",
    specialization: ["VLSI Design", "FPGA Prototyping", "Low Power CMOS"],
    subjectsHandled: ["VLSI Design", "Digital Signal Processing", "Electronic Devices"],
    rating: 4.5,
    reviewCount: 24,
    isAcceptingStudents: true,
    bio: "Leads the VLSI CAD Lab at MLRIT. Mentors students on Cadence and Xilinx FPGA tape-out projects.",
  },
];

// ─── Seed Faculty Reviews ────────────────────────────────────────────────────

export const SEED_FACULTY_REVIEWS: FacultyReview[] = [
  {
    id: "rev-fac-001",
    facultyId: "fac-cse-001",
    studentId: "user-std-101",
    studentName: "Anonymous Student",
    isAnonymous: true,
    rating: 5,
    tags: ["Clear Explanations", "Helpful Office Hours", "Real-world Examples"],
    comment: "Dr. Srinivas Rao explains transaction recovery and B+ tree indexing with fantastic real-life database server examples. Highly recommend attending his office hours if you have project questions.",
    semester: 5,
    academicYear: "2024-2025",
    createdAt: "2026-08-20T10:00:00Z",
  },
  {
    id: "rev-fac-002",
    facultyId: "fac-cse-001",
    studentId: "user-std-102",
    studentName: "Sneha Varma",
    isAnonymous: false,
    rating: 5,
    tags: ["Inspirational", "Fair Grading", "Interactive"],
    comment: "One of the best professors in the CSE department. Encourages students to write research papers and is always willing to clear doubts even after class hours.",
    semester: 5,
    academicYear: "2024-2025",
    createdAt: "2026-08-22T14:30:00Z",
  },
  {
    id: "rev-fac-003",
    facultyId: "fac-cse-002",
    studentId: "user-std-103",
    studentName: "Anonymous Student",
    isAnonymous: true,
    rating: 4,
    tags: ["Practical Labs", "Clear Slides", "Strict Attendance"],
    comment: "Prof. Lakshmi's Wireshark lab assignments are very practical. Make sure you don't miss classes as attendance is strictly monitored.",
    semester: 6,
    academicYear: "2024-2025",
    createdAt: "2026-08-25T11:00:00Z",
  },
  {
    id: "rev-fac-004",
    facultyId: "fac-ece-001",
    studentId: "user-std-201",
    studentName: "Anonymous Student",
    isAnonymous: true,
    rating: 5,
    tags: ["Master of Subject", "Engaging", "Practical Approach"],
    comment: "Dr. Sudhakar makes 8086 assembly language feel intuitive. His live coding demonstrations during class make difficult pin-diagram concepts crystal clear.",
    semester: 5,
    academicYear: "2024-2025",
    createdAt: "2026-08-21T16:00:00Z",
  },
];

// ─── Seed Study Groups ───────────────────────────────────────────────────────

export const SEED_STUDY_GROUPS: StudyGroup[] = [
  // ── CSE Study Groups ──
  {
    id: "sg-cse-001",
    name: "DBMS & OS Mid-Term Prep Squad",
    description: "Focused study group solving previous year question papers, practicing normalization problems, and discussing memory management questions together.",
    departmentId: "cse",
    subjectCode: "CS501PC",
    subjectName: "Database Management Systems",
    semester: 5,
    leaderId: "user-std-101",
    leaderName: "K. Rohit Reddy",
    membersCount: 8,
    maxMembers: 12,
    meetingLink: "https://meet.google.com/abc-defg-hij",
    meetingSchedule: "Every Tue & Thu @ 6:00 PM IST",
    isPrivate: false,
    tags: ["DBMS", "OS", "Mid-Terms", "Question Solving"],
    createdAt: "2026-08-14T10:00:00Z",
  },
  {
    id: "sg-cse-002",
    name: "Competitive Algorithms & DAA Mastery",
    description: "Deep dive into dynamic programming, graph algorithms, and LeetCode medium/hard problems aligned with our DAA curriculum.",
    departmentId: "cse",
    subjectCode: "CS503PC",
    subjectName: "Design and Analysis of Algorithms",
    semester: 5,
    leaderId: "user-std-104",
    leaderName: "Ananya Deshmukh",
    membersCount: 10,
    maxMembers: 15,
    meetingLink: "https://meet.google.com/daa-algo-club",
    meetingSchedule: "Saturdays @ 4:00 PM IST",
    isPrivate: false,
    tags: ["DAA", "Algorithms", "Dynamic Programming", "LeetCode"],
    createdAt: "2026-08-16T12:30:00Z",
  },
  {
    id: "sg-cse-003",
    name: "Full Stack Web Dev Cohort (Semester 6)",
    description: "Building production-ready full stack web applications, sharing code reviews, and collaborating on semester capstone projects.",
    departmentId: "cse",
    subjectCode: "CS602PC",
    subjectName: "Web Technologies",
    semester: 6,
    leaderId: "user-std-105",
    leaderName: "Pranav Joshi",
    membersCount: 6,
    maxMembers: 10,
    meetingSchedule: "Sundays @ 5:00 PM IST",
    isPrivate: false,
    tags: ["React", "NextJS", "NodeJS", "Projects"],
    createdAt: "2026-08-20T14:00:00Z",
  },

  // ── ECE Study Groups ──
  {
    id: "sg-ece-001",
    name: "Microprocessors 8086 Assembly Lab Group",
    description: "Hands-on assembly coding sessions and hardware kit interfacing problem-solving for 5th semester ECE students.",
    departmentId: "ece",
    subjectCode: "EC501PC",
    subjectName: "Microprocessors and Microcontrollers",
    semester: 5,
    leaderId: "user-std-201",
    leaderName: "T. Manasa",
    membersCount: 6,
    maxMembers: 10,
    meetingSchedule: "Mon & Wed @ 5:30 PM IST",
    isPrivate: false,
    tags: ["8086", "Assembly", "Lab Prep"],
    createdAt: "2026-08-15T11:00:00Z",
  },
  {
    id: "sg-ece-002",
    name: "VLSI Cadence Layout Design Circle",
    description: "Practicing CMOS stick diagrams, layout design rules, and Verilog simulation in Cadence Virtuoso tools.",
    departmentId: "ece",
    subjectCode: "EC601PC",
    subjectName: "VLSI Design",
    semester: 6,
    leaderId: "user-std-202",
    leaderName: "G. Karthik",
    membersCount: 5,
    maxMembers: 8,
    meetingSchedule: "Fridays @ 6:00 PM IST",
    isPrivate: false,
    tags: ["VLSI", "Cadence", "Verilog"],
    createdAt: "2026-08-18T16:00:00Z",
  },
];

// ─── Seed Academic Events (Calendar) ─────────────────────────────────────────

export const SEED_ACADEMIC_EVENTS: AcademicEvent[] = [
  // College-wide events (visible to all)
  {
    id: "event-col-001",
    title: "Mid-Term Examinations (Semesters 3, 5, 7)",
    description: "Official mid-term examinations for all engineering branches. Timetables available on the student notice board.",
    scope: "college",
    eventType: "EXAM",
    startDate: "2026-09-22T09:30:00Z",
    endDate: "2026-09-29T16:30:00Z",
    location: "Examination Halls (Blocks A, B, C)",
    isImportant: true,
  },
  {
    id: "event-col-002",
    title: "Gandhi Jayanti & Dussehra Vacation",
    description: "College closed for national holiday and autumn vacation.",
    scope: "college",
    eventType: "HOLIDAY",
    startDate: "2026-10-02T00:00:00Z",
    endDate: "2026-10-06T23:59:59Z",
    isImportant: false,
  },
  {
    id: "event-col-003",
    title: "Annual Technical Symposium & Hackathon",
    description: "Flagship 36-hour inter-college hackathon and technical paper presentations with prizes worth ₹2,00,000.",
    scope: "college",
    eventType: "FEST",
    startDate: "2026-10-18T09:00:00Z",
    endDate: "2026-10-19T18:00:00Z",
    location: "Main Auditorium & Computing Center",
    isImportant: true,
  },

  // Department-specific events: CSE
  {
    id: "event-dept-cse-001",
    title: "CSE DBMS Mini-Project Submission Deadline",
    description: "All 5th semester students must submit their full stack database project code and documentation on GitHub and the college portal.",
    scope: "department",
    departmentId: "cse",
    eventType: "SUBMISSION",
    startDate: "2026-09-18T23:59:59Z",
    endDate: "2026-09-18T23:59:59Z",
    location: "Online Portal / CSE Department",
    isImportant: true,
  },
  {
    id: "event-dept-cse-002",
    title: "Guest Lecture: Scalable Microservices with Google Cloud",
    description: "Technical talk by Principal Cloud Architect from Google on distributed systems and container orchestration.",
    scope: "department",
    departmentId: "cse",
    eventType: "GUEST_LECTURE",
    startDate: "2026-09-25T14:00:00Z",
    endDate: "2026-09-25T16:00:00Z",
    location: "Seminar Hall 2, Block A",
    isImportant: false,
  },

  // Department-specific events: ECE
  {
    id: "event-dept-ece-001",
    title: "ECE 8086 Microprocessor Lab Internal Evaluation",
    description: "Hands-on assembly coding test and viva voce for all 5th semester ECE students.",
    scope: "department",
    departmentId: "ece",
    eventType: "EXAM",
    startDate: "2026-09-20T10:00:00Z",
    endDate: "2026-09-20T13:00:00Z",
    location: "Microprocessor Lab, Block B - Room 204",
    isImportant: true,
  },
  {
    id: "event-dept-ece-002",
    title: "Hands-on Workshop: VLSI Physical Design with Cadence",
    description: "One-day practical workshop on chip layout generation and DRC/LVS checks.",
    scope: "department",
    departmentId: "ece",
    eventType: "WORKSHOP",
    startDate: "2026-09-28T09:30:00Z",
    endDate: "2026-09-28T17:00:00Z",
    location: "VLSI CAD Lab, Block B",
    isImportant: false,
  },
];

// ─── Seed Campus Wiki Articles (Shared Across College) ───────────────────────

export const SEED_WIKI_ARTICLES: WikiArticle[] = [
  {
    id: "wiki-001",
    slug: "academic-grading-and-cgpa-calculation-guide",
    title: "Academic Grading System, CGPA Calculation & Credits Guide",
    category: "ACADEMIC_POLICIES",
    content: `# Academic Grading System & CGPA Guide

## 1. Grading Scale
MLRIT follows a 10-point letter grading system:

| Letter Grade | Grade Point | Marks Range | Performance |
| :--- | :--- | :--- | :--- |
| **O** (Outstanding) | 10 | 90% and above | Exceptional |
| **A+** (Excellent) | 9 | 80% - 89% | Outstanding |
| **A** (Very Good) | 8 | 70% - 79% | Excellent |
| **B+** (Good) | 7 | 60% - 69% | Above Average |
| **B** (Average) | 6 | 50% - 59% | Pass |
| **C** (Satisfactory) | 5 | 40% - 49% | Marginal Pass |
| **F** (Fail) | 0 | Below 40% | Re-examination Required |

## 2. SGPA Calculation Formula
$$\\text{SGPA} = \\frac{\\sum (C_i \\times G_i)}{\\sum C_i}$$
Where $C_i$ is the credit for course $i$ and $G_i$ is the grade point secured.

## 3. Minimum Attendance Requirement
- Minimum **75% attendance** is mandatory in all registered theory and lab courses.
- Condonation for medical reasons (65% to 74%) requires verified medical certificates submitted to the Dean Academics office within 3 working days.`,
    authorId: "user-admin-01",
    authorName: "Academic Section Admin",
    tags: ["Grading", "CGPA", "SGPA", "Attendance", "Policy"],
    helpfulCount: 142,
    viewsCount: 1850,
    createdAt: "2026-07-01T08:00:00Z",
  },
  {
    id: "wiki-002",
    slug: "central-library-facilities-and-digital-access",
    title: "Central Library Facilities, IEEE Xplore & Digital Borrowing",
    category: "CAMPUS_GUIDE",
    content: `# Central Library Guide & Digital Access

## Overview
The Central Library spans over 3 floors in the Administrative Block with over 60,000 volumes, print journals, and high-speed Wi-Fi research cubicles.

## Operating Hours
- **Monday to Friday:** 8:00 AM – 8:00 PM
- **Saturdays:** 9:00 AM – 5:00 PM
- **Examination Periods:** Extended hours till 10:00 PM

## Digital Subscriptions & Remote Access
All enrolled students have institutional credentials for:
1. **IEEE Xplore Digital Library**
2. **SpringerLink & ScienceDirect**
3. **DELNET & NPTEL Local Video Servers**

To access off-campus, use the college OpenAthens proxy gateway with your \`@mlrit.ac.in\` email account.`,
    authorId: "user-admin-01",
    authorName: "Central Library Desk",
    tags: ["Library", "IEEE", "Books", "Digital Access", "Study Rooms"],
    helpfulCount: 98,
    viewsCount: 1220,
    createdAt: "2026-07-10T10:00:00Z",
  },
  {
    id: "wiki-003",
    slug: "lab-safety-protocols-and-equipment-booking",
    title: "Engineering Lab Protocols, Hardware Kits & Safety Rules",
    category: "LAB_PROTOCOLS",
    content: `# Engineering Lab Protocols & Safety Guidelines

## General Rules
1. **Dress Code:** Closed-toe shoes and college lab coats are strictly mandatory in Chemistry, Physics, and Mechanical Workshops.
2. **Hardware Handling:** ESD wrist straps must be worn when working with FPGA boards or sensitive ICs in VLSI and Microprocessor labs.
3. **Equipment Check-out:** Oscilloscopes, logic analyzers, and sensor kits must be signed out from the lab technician with student ID card deposit.`,
    authorId: "user-coord-01",
    authorName: "Dr. K. Srinivas Rao",
    tags: ["Lab Safety", "Hardware", "Protocols", "Equipment"],
    helpfulCount: 45,
    viewsCount: 680,
    createdAt: "2026-07-15T12:00:00Z",
  },
];

// ─── Seed Academic Requests ──────────────────────────────────────────────────

export const SEED_ACADEMIC_REQUESTS: AcademicRequest[] = [
  // ── CSE Requests ──
  {
    id: "req-cse-001",
    title: "Looking for Unit 4 & 5 handwritten notes for OS Virtual Memory",
    description: "Need clear solved examples on Page Fault calculations (FIFO vs LRU vs Second Chance) for our upcoming internal exam.",
    departmentId: "cse",
    subjectCode: "CS502PC",
    subjectName: "Operating Systems",
    semester: 5,
    resourceType: "NOTE",
    requesterId: "user-std-103",
    requesterName: "V. Sai Kumar",
    requesterDepartment: "Computer Science & Engineering",
    status: "OPEN",
    commentsCount: 3,
    upvotesCount: 14,
    createdAt: "2026-08-27T10:00:00Z",
  },
  {
    id: "req-cse-002",
    title: "Need DAA 2024 End-Semester Question Paper with Solutions",
    description: "Specifically looking for the solution to the 15-mark dynamic programming matrix chain multiplication problem.",
    departmentId: "cse",
    subjectCode: "CS503PC",
    subjectName: "Design and Analysis of Algorithms",
    semester: 5,
    resourceType: "PYQ",
    requesterId: "user-std-102",
    requesterName: "Sneha Varma",
    requesterDepartment: "Computer Science & Engineering",
    status: "FULFILLED",
    fulfilledResourceId: "res-cse-004",
    fulfilledResourceTitle: "DAA Complete Lab Manual with C++ & Python Code",
    commentsCount: 2,
    upvotesCount: 8,
    createdAt: "2026-08-20T11:30:00Z",
  },

  // ── ECE Requests ──
  {
    id: "req-ece-001",
    title: "Requesting 8051 Microcontroller Timer & Counter Mode Programming Guide",
    description: "Need assembly and C examples for generating square waves using Timer 0 in Mode 2 (Auto-reload).",
    departmentId: "ece",
    subjectCode: "EC501PC",
    subjectName: "Microprocessors and Microcontrollers",
    semester: 5,
    resourceType: "NOTE",
    requesterId: "user-std-202",
    requesterName: "G. Karthik",
    requesterDepartment: "Electronics & Communication Engineering",
    status: "OPEN",
    commentsCount: 1,
    upvotesCount: 9,
    createdAt: "2026-08-26T15:00:00Z",
  },
];
