/**
 * CampusNexus — Moderation & Admin Seed Data
 * Phase 10 Initial Reports, Audit Logs, and User Management Data
 */

import { ModerationReport, ModerationAuditEntry, ManagedUser } from "@/types/moderation.types";

export const INITIAL_REPORTS: ModerationReport[] = [
  {
    id: "rep-001",
    targetType: "POST",
    targetId: "post-1",
    reason: "SPAM",
    description: "External paid tutoring service link posted repeatedly in general channel.",
    reportedByUserId: "mock-student-001",
    status: "OPEN",
    contentSnippet: "Looking for study partners for Operating Systems CSE 301 midterms! (Check out external link...)",
    authorId: "mock-student-002",
    authorName: "Rohan Sharma",
    isAuthorAnonymous: false,
    createdAt: "2024-02-16T10:15:00Z",
  },
  {
    id: "rep-002",
    targetType: "COMMENT",
    targetId: "comment-3",
    reason: "HARASSMENT",
    description: "Disrespectful remarks directed at a student asking a basic academic question.",
    reportedByUserId: "mock-student-001",
    status: "UNDER_REVIEW",
    contentSnippet: "Why can't you just read the textbook instead of asking obvious questions?",
    authorId: "mock-student-003",
    authorName: "Anonymous Student",
    isAuthorAnonymous: true,
    createdAt: "2024-02-15T14:30:00Z",
    reviewedByUserId: "mock-mod-001",
    reviewedByUserName: "Sam Patel",
    reviewedAt: "2024-02-15T16:00:00Z",
    moderationNotes: "Investigating user comment history for repeated violations.",
  },
  {
    id: "rep-003",
    targetType: "POST",
    targetId: "post-5",
    reason: "MISINFORMATION",
    description: "Claimed tomorrow is an unscheduled college holiday without any official circular.",
    reportedByUserId: "mock-mod-001",
    status: "RESOLVED",
    contentSnippet: "Heard from senior coordinators that classes are canceled tomorrow.",
    authorId: "mock-student-002",
    authorName: "Rohan Sharma",
    isAuthorAnonymous: false,
    createdAt: "2024-02-12T09:00:00Z",
    reviewedByUserId: "mock-admin-001",
    reviewedByUserName: "Jordan Smith",
    reviewedAt: "2024-02-12T10:30:00Z",
    moderationNotes: "Official notice verified; post annotated and marked resolved.",
    actionTaken: "CONTENT_RESTORED",
  },
  {
    id: "rep-004",
    targetType: "EVENT",
    targetId: "evt-99",
    reason: "INAPPROPRIATE",
    description: "Unofficial private gaming meetup advertised as an institutional robotics workshop.",
    reportedByUserId: "mock-student-001",
    status: "DISMISSED",
    contentSnippet: "LAN Gaming Night in Hostels Block B.",
    authorId: "mock-student-002",
    authorName: "Rohan Sharma",
    isAuthorAnonymous: false,
    createdAt: "2024-02-08T18:00:00Z",
    reviewedByUserId: "mock-mod-001",
    reviewedByUserName: "Sam Patel",
    reviewedAt: "2024-02-08T19:30:00Z",
    moderationNotes: "Club advisor confirmed sanctioned recreational club social hour.",
    actionTaken: "REPORT_DISMISSED",
  },
];

export const INITIAL_AUDIT_LOGS: ModerationAuditEntry[] = [
  {
    id: "aud-001",
    actorId: "mock-admin-001",
    actorName: "Jordan Smith",
    actorRole: "ADMIN",
    action: "REPORT_RESOLVED",
    targetType: "POST",
    targetId: "post-5",
    targetSummary: "Claimed unscheduled college holiday without official circular",
    reason: "Official college notice verified; clarified notice pinned.",
    createdAt: "2024-02-12T10:30:00Z",
  },
  {
    id: "aud-002",
    actorId: "mock-mod-001",
    actorName: "Sam Patel",
    actorRole: "MODERATOR",
    action: "REPORT_DISMISSED",
    targetType: "EVENT",
    targetId: "evt-99",
    targetSummary: "LAN Gaming Night advertised in campus events",
    reason: "Confirmed sanctioned club recreational event by advisor.",
    createdAt: "2024-02-08T19:30:00Z",
  },
  {
    id: "aud-003",
    actorId: "mock-mod-001",
    actorName: "Sam Patel",
    actorRole: "MODERATOR",
    action: "SUPPORT_REPLIED",
    targetType: "SUPPORT_REQUEST",
    targetId: "req-101",
    targetSummary: "Unable to download Lab Manual for Operating Systems",
    reason: "Contacted department coordinator for updated PDF upload.",
    createdAt: "2024-02-11T09:15:00Z",
  },
  {
    id: "aud-004",
    actorId: "mock-admin-001",
    actorName: "Jordan Smith",
    actorRole: "ADMIN",
    action: "USER_SUSPENDED",
    targetType: "USER",
    targetId: "mock-student-003",
    targetSummary: "Priya Verma (@priya_v)",
    reason: "Repeated spam links and abusive comment behavior after formal warning.",
    createdAt: "2024-02-10T12:00:00Z",
  },
];

export const INITIAL_MANAGED_USERS: ManagedUser[] = [
  {
    id: "mock-student-001",
    username: "student_mlrit",
    email: "student@mlrit.ac.in",
    fullName: "Alex Johnson",
    role: "STUDENT",
    department: "Computer Science & Engineering",
    batch: "2022-2026",
    isVerified: true,
    followersCount: 42,
    followingCount: 18,
    badges: [],
    clubLeaderOf: [],
    createdAt: "2022-08-01T00:00:00Z",
    accountStatus: "ACTIVE",
  },
  {
    id: "mock-mod-001",
    username: "mod_mlrit",
    email: "moderator@mlrit.ac.in",
    fullName: "Sam Patel",
    role: "MODERATOR",
    department: "Electronics & Communication Engineering",
    batch: "2021-2025",
    isVerified: true,
    followersCount: 87,
    followingCount: 35,
    badges: [],
    clubLeaderOf: [],
    createdAt: "2021-08-01T00:00:00Z",
    accountStatus: "ACTIVE",
  },
  {
    id: "mock-admin-001",
    username: "admin_mlrit",
    email: "admin@mlrit.ac.in",
    fullName: "Jordan Smith",
    role: "ADMIN",
    department: "Administration",
    isVerified: true,
    followersCount: 210,
    followingCount: 60,
    badges: [],
    clubLeaderOf: [],
    createdAt: "2020-01-01T00:00:00Z",
    accountStatus: "ACTIVE",
  },
  {
    id: "mock-student-002",
    username: "rohan_s",
    email: "rohan.s@mlrit.ac.in",
    fullName: "Rohan Sharma",
    role: "STUDENT",
    department: "Information Technology",
    batch: "2023-2027",
    isVerified: true,
    followersCount: 15,
    followingCount: 22,
    badges: [],
    clubLeaderOf: [],
    createdAt: "2023-08-01T00:00:00Z",
    accountStatus: "ACTIVE",
  },
  {
    id: "mock-student-003",
    username: "priya_v",
    email: "priya.v@mlrit.ac.in",
    fullName: "Priya Verma",
    role: "STUDENT",
    department: "Artificial Intelligence & Data Science",
    batch: "2022-2026",
    isVerified: true,
    followersCount: 30,
    followingCount: 45,
    badges: [],
    clubLeaderOf: [],
    createdAt: "2022-08-01T00:00:00Z",
    accountStatus: "SUSPENDED",
    suspendedAt: "2024-02-10T12:00:00Z",
    suspensionReason: "Repeated spam links and abusive comment behavior after formal warning.",
  },
];
