import {
  Club,
  ClubMembership,
  CampusEvent,
  SportsActivity,
  SportsFacility,
  SportsTournament,
  CampusFacility,
  LostFoundItem,
  MarketplaceListing,
  TransportRoute,
  HostelInfo,
  CampusDirectoryEntry,
} from "@/types/campus-life.types";

// ─── 1. The Exact 9 College-Wide Clubs (No Department Properties) ─────────────

export const SEED_CLUBS: Club[] = [
  {
    id: "club-came",
    name: "CAME",
    tagline: "Creativity, Arts, Media & Entertainment Society",
    description: "The premier college-wide creative arts, digital media, photography, and theatrical performances society open to all students across campus.",
    about: "CAME serves as the vibrant cultural and multimedia hub for the entire institution. We organize campus photography exhibitions, short filmmaking festivals, graphic design bootcamps, open-mic nights, and stage plays. Every student with a passion for creative expression is welcome regardless of branch or year.",
    category: "CULTURAL",
    facultyCoordinator: "Dr. K. Srinivas (Humanities & Cultural Affairs)",
    leaders: [
      {
        id: "came-lead-1",
        name: "Aarav Sharma",
        roleTitle: "President",
        department: "Mechanical Engineering",
        year: 4,
      },
      {
        id: "came-lead-2",
        name: "Sneha Reddy",
        roleTitle: "Vice President",
        department: "Electronics & Communication",
        year: 3,
      },
    ],
    membershipCount: 342,
    activities: [
      "Annual Short Film Contest",
      "Street Play & Theatrics Workshop",
      "Digital Art & Motion Graphics Masterclass",
      "Campus Unfiltered Photo Walks",
    ],
    contactEmail: "came.club@campusnexus.edu",
    meetingSchedule: "Every Wednesday at 4:30 PM",
    roomVenue: "SAC Multi-Purpose Studio (Room 102)",
    createdAt: "2024-01-15T00:00:00.000Z",
  },
  {
    id: "club-ewb",
    name: "EWB",
    tagline: "Engineers Without Borders — Campus Chapter",
    description: "Student-driven community engineering initiatives focusing on clean water, renewable energy, and sustainable village development.",
    about: "The EWB chapter unites engineers across all disciplines to solve real-world community challenges. Our active projects include rainwater harvesting prototypes for neighboring schools, solar illumination setups, and e-waste awareness drives.",
    category: "SOCIAL",
    facultyCoordinator: "Dr. M. Lakshmi (Civil & Environmental)",
    leaders: [
      {
        id: "ewb-lead-1",
        name: "Rohan Varma",
        roleTitle: "Chapter Lead",
        department: "Electrical Engineering",
        year: 4,
      },
      {
        id: "ewb-lead-2",
        name: "Ananya Rao",
        roleTitle: "Projects Coordinator",
        department: "Computer Science",
        year: 3,
      },
    ],
    membershipCount: 268,
    activities: [
      "Rural Technology Outreach Camps",
      "Solar Charging Station Builds",
      "Clean Campus Water Audit",
      "Sustainability Hackathon",
    ],
    contactEmail: "ewb.chapter@campusnexus.edu",
    meetingSchedule: "Alternate Saturdays at 10:00 AM",
    roomVenue: "Environmental Studies Lab (Room 304)",
    createdAt: "2024-01-20T00:00:00.000Z",
  },
  {
    id: "club-apex",
    name: "Apex",
    tagline: "Robotics, Automation & Hardware Innovation Consortium",
    description: "The premier student robotics and automated systems community designing autonomous bots, drones, and IoT hardware.",
    about: "Apex is the central robotics society representing the college at national and international bot battles, drone races, and hardware hackathons. We provide hardware toolkits, 3D printers, PCB prototyping labs, and hands-on guidance for all aspiring roboticists.",
    category: "TECHNICAL",
    facultyCoordinator: "Prof. P. Ramachandran (Mechatronics)",
    leaders: [
      {
        id: "apex-lead-1",
        name: "Vikram Malhotra",
        roleTitle: "Captain / Lead Engineer",
        department: "Electronics & Communication",
        year: 4,
      },
      {
        id: "apex-lead-2",
        name: "Meera Nair",
        roleTitle: "Firmware Lead",
        department: "Computer Science",
        year: 3,
      },
    ],
    membershipCount: 310,
    activities: [
      "Autonomous Robowars Championship",
      "FPV Drone Racing League",
      "Embedded Systems & ROS Workshop",
      "Hardware Hackathon 36-Hour Sprint",
    ],
    contactEmail: "apex.robotics@campusnexus.edu",
    meetingSchedule: "Tuesdays & Fridays at 5:00 PM",
    roomVenue: "Robotics & Prototyping Workshop (Block-B Ground Floor)",
    createdAt: "2024-01-10T00:00:00.000Z",
  },
  {
    id: "club-sports",
    name: "Sports",
    tagline: "Campus Sports Council & Athletic Federation",
    description: "The college-wide athletic council driving intramural leagues, varsity selections, physical fitness bootcamps, and inter-collegiate tournaments.",
    about: "The Sports Club coordinates all collegiate sports squads including cricket, football, basketball, badminton, table tennis, volleyball, athletics, and chess. We organize the prestigious Annual Inter-Year Sports Fest and manage daily evening coaching sessions.",
    category: "SPORTS",
    facultyCoordinator: "Coach Rajesh Singh (Physical Education Director)",
    leaders: [
      {
        id: "sports-lead-1",
        name: "Karthik Reddy",
        roleTitle: "Sports Secretary",
        department: "Information Technology",
        year: 4,
      },
      {
        id: "sports-lead-2",
        name: "Pooja Hegde",
        roleTitle: "Athletics Coordinator",
        department: "Civil Engineering",
        year: 3,
      },
    ],
    membershipCount: 520,
    activities: [
      "Annual Inter-Year Cricket Cup",
      "Inter-College Basketball Championship",
      "Campus 5K Marathon for Wellness",
      "Intramural Badminton & Table Tennis Open",
    ],
    contactEmail: "sports.council@campusnexus.edu",
    meetingSchedule: "Daily Practice Sessions at 4:45 PM",
    roomVenue: "Indoor Sports Complex & Stadium Pavilion",
    createdAt: "2024-01-05T00:00:00.000Z",
  },
  {
    id: "club-scope",
    name: "SCOPE",
    tagline: "Society for Competitive Programming & Open-Source Engineering",
    description: "Dedicated to competitive coding, algorithmic problem solving, Google Summer of Code mentorship, and system design.",
    about: "SCOPE nurtures the college's top algorithmists and software engineers. We conduct weekly Codeforces/LeetCode contests, system architecture roundtables, and guided open-source contribution cohorts for students across all engineering branches.",
    category: "TECHNICAL",
    facultyCoordinator: "Dr. B. Venkat (Computer Engineering)",
    leaders: [
      {
        id: "scope-lead-1",
        name: "Aditya Nambiar",
        roleTitle: "Lead Algorist",
        department: "Computer Science",
        year: 4,
      },
      {
        id: "scope-lead-2",
        name: "Harshitha Goud",
        roleTitle: "Open-Source Lead",
        department: "Information Technology",
        year: 3,
      },
    ],
    membershipCount: 415,
    activities: [
      "Weekly Campus Code Sprint (ICPC Style)",
      "Open Source Contribution Bootcamp",
      "Advanced Dynamic Programming Series",
      "Campus HackNight 24-Hour Build",
    ],
    contactEmail: "scope.coding@campusnexus.edu",
    meetingSchedule: "Thursdays at 5:00 PM & Sundays 10:00 AM",
    roomVenue: "Central Computing Facility Lab-4",
    createdAt: "2024-01-12T00:00:00.000Z",
  },
  {
    id: "club-nss",
    name: "NSS",
    tagline: "National Service Scheme — Not Me, But You",
    description: "The official institutional community outreach, disaster relief preparedness, social awareness, and civic volunteering wing.",
    about: "NSS volunteers actively lead blood donation drives, village educational adoption programs, tree plantation camps, environmental cleanliness campaigns, and health check-up camps serving both the campus and neighboring local communities.",
    category: "COMMUNITY",
    facultyCoordinator: "Dr. S. K. Murthy (NSS Programme Officer)",
    leaders: [
      {
        id: "nss-lead-1",
        name: "Suresh Babu",
        roleTitle: "Student Convener",
        department: "Civil Engineering",
        year: 4,
      },
      {
        id: "nss-lead-2",
        name: "Divya Teja",
        roleTitle: "Outreach Head",
        department: "Electronics & Communication",
        year: 3,
      },
    ],
    membershipCount: 480,
    activities: [
      "Mega Annual Blood Donation Camp",
      "Haritha Haram Tree Plantation Drive",
      "Free Health & Eye Screening Camp",
      "Digital Literacy Sessions in Rural Schools",
    ],
    contactEmail: "nss.unit@campusnexus.edu",
    meetingSchedule: "Saturdays at 2:00 PM",
    roomVenue: "NSS Central Cell (SAC Room 201)",
    createdAt: "2024-01-08T00:00:00.000Z",
  },
  {
    id: "club-cie",
    name: "CIE",
    tagline: "Center for Innovation & Entrepreneurship",
    description: "The startup incubator, venture accelerator, and investor pitching cell empowering campus innovators and founders.",
    about: "CIE bridges the gap between campus tech projects and viable commercial enterprises. We host startup pitch decks, angel investor connect days, IP/patent filing guidance sessions, and entrepreneurial fireside chats with successful alumni founders.",
    category: "ENTREPRENEURSHIP",
    facultyCoordinator: "Prof. Anant Deshmukh (Incubation Director)",
    leaders: [
      {
        id: "cie-lead-1",
        name: "Varun Kulkarni",
        roleTitle: "President",
        department: "Computer Science",
        year: 4,
      },
      {
        id: "cie-lead-2",
        name: "Priyanka Sen",
        roleTitle: "Venture Associate",
        department: "Mechanical Engineering",
        year: 3,
      },
    ],
    membershipCount: 295,
    activities: [
      "Campus Shark Tank & Seed Pitch Fest",
      "Product Validation & MVP Clinic",
      "Alumni Founder Spotlight Sessions",
      "Intellectual Property & Patent Workshops",
    ],
    contactEmail: "cie.incubator@campusnexus.edu",
    meetingSchedule: "Mondays at 4:30 PM",
    roomVenue: "Innovation & Incubation Lounge (Block-E 2nd Floor)",
    createdAt: "2024-01-18T00:00:00.000Z",
  },
  {
    id: "club-club-literati",
    name: "Club Literati",
    tagline: "Debating, Model UN, Creative Writing & Literary Society",
    description: "The intellectual home for parliamentary debate, elocution, creative writing, poetry slams, and Model United Nations delegations.",
    about: "Club Literati fosters critical thinking, rhetoric eloquence, and expressive journalism. We publish the campus literary magazine, host parliamentary debate tournaments, conduct creative writing circles, and train delegates for national Model UN conferences.",
    category: "LITERARY",
    facultyCoordinator: "Dr. Geetha Swaminathan (English & Communication)",
    leaders: [
      {
        id: "literati-lead-1",
        name: "Shreya Mukherjee",
        roleTitle: "President / Debating Secretary",
        department: "Computer Science",
        year: 4,
      },
      {
        id: "literati-lead-2",
        name: "Ishaan Gupta",
        roleTitle: "Editor-in-Chief",
        department: "Information Technology",
        year: 3,
      },
    ],
    membershipCount: 230,
    activities: [
      "Annual Inter-College Parliamentary Debate",
      "Campus Model United Nations (CMUN)",
      "Spoken Word Poetry & Storytelling Slam",
      "Campus Chronicle Literary Journal Release",
    ],
    contactEmail: "literati.club@campusnexus.edu",
    meetingSchedule: "Fridays at 4:15 PM",
    roomVenue: "Central Library Seminar Room (2nd Floor)",
    createdAt: "2024-01-22T00:00:00.000Z",
  },
  {
    id: "club-csi",
    name: "CSI",
    tagline: "Computer Society of India — Campus Chapter",
    description: "The premier technical society organizing national symposiums, hackathons, cloud certifications, and tech workshops.",
    about: "The CSI student chapter is one of the largest technical bodies on campus. We host our flagship annual techno-cultural symposium, developer conferences, DevOps masterclasses, cybersecurity capture-the-flag competitions, and industry expert panels.",
    category: "TECHNICAL",
    facultyCoordinator: "Dr. T. Ravindra (Computer Science & Engineering)",
    leaders: [
      {
        id: "csi-lead-1",
        name: "Nikhil Joshi",
        roleTitle: "Chairman",
        department: "Computer Science",
        year: 4,
      },
      {
        id: "csi-lead-2",
        name: "Tanvi Mathur",
        roleTitle: "Vice Chair",
        department: "Information Technology",
        year: 3,
      },
    ],
    membershipCount: 490,
    activities: [
      "Flagship National Tech Symposium",
      "HackNexus 36-Hour National Hackathon",
      "Cloud Architect & DevOps Hands-on Lab",
      "CyberSecurity Capture The Flag (CTF)",
    ],
    contactEmail: "csi.chapter@campusnexus.edu",
    meetingSchedule: "Tuesdays at 4:30 PM",
    roomVenue: "Auditorium Annex & Central Lab-1",
    createdAt: "2024-01-02T00:00:00.000Z",
  },
];

// ─── 2. Unified Events Seed Data (Club, Campus, Sports) ───────────────────────

export const SEED_EVENTS: CampusEvent[] = [
  {
    id: "evt-csi-hacknexus",
    title: "HackNexus 2026 — 36-Hour National Hackathon",
    description: "Build cutting-edge solutions across AI, Web3, Smart Campus, and Climate Tech. Grand prizes worth ₹1,50,000, industry mentorship, and direct internship opportunities.",
    eventType: "CLUB",
    category: "TECHNICAL",
    organizer: "CSI",
    organizerId: "club-csi",
    startDate: "2026-10-15",
    endDate: "2026-10-17",
    startTime: "09:00 AM",
    endTime: "06:00 PM",
    location: "Central Computing Facility Labs 1-4",
    status: "UPCOMING",
    capacity: 250,
    registeredCount: 184,
    registrationDeadline: "2026-10-10T23:59:59.000Z",
    isRegistrationOpen: true,
    registrationFee: 0,
    tags: ["Hackathon", "AI", "Open-Source", "Software"],
    requirements: ["Laptop with charger", "College ID Card", "Team of 2-4 students"],
    createdAt: "2026-08-15T00:00:00.000Z",
    updatedAt: "2026-08-15T00:00:00.000Z",
  },
  {
    id: "evt-sports-cricket-cup",
    title: "Annual Inter-Year Cricket Championship 2026",
    description: "The most anticipated T20 cricket tournament of the year. 8 teams battling for the coveted CampusNexus Trophy across 4 action-packed weekends.",
    eventType: "SPORTS",
    category: "SPORTS",
    organizer: "Sports",
    organizerId: "club-sports",
    startDate: "2026-10-04",
    endDate: "2026-10-25",
    startTime: "07:30 AM",
    endTime: "05:30 PM",
    location: "Main Sports Stadium & Ground",
    status: "UPCOMING",
    capacity: 120,
    registeredCount: 96,
    registrationDeadline: "2026-09-30T23:59:59.000Z",
    isRegistrationOpen: true,
    registrationFee: 0,
    tags: ["Cricket", "Tournament", "T20", "Athletics"],
    requirements: ["White cricket apparel", "Valid student ID card", "Fitness clearance"],
    sportsMetadata: {
      sportName: "Cricket",
      fixtureType: "League + Knockout",
    },
    createdAt: "2026-08-20T00:00:00.000Z",
    updatedAt: "2026-08-20T00:00:00.000Z",
  },
  {
    id: "evt-literati-mun",
    title: "Campus Model United Nations (CMUN) 2026",
    description: "Simulating global diplomacy, international security, and human rights committees. Deliberate on global crises and hone public speaking.",
    eventType: "CLUB",
    category: "LITERARY",
    organizer: "Club Literati",
    organizerId: "club-club-literati",
    startDate: "2026-10-20",
    endDate: "2026-10-21",
    startTime: "09:30 AM",
    endTime: "05:00 PM",
    location: "Main Auditorium & Seminar Halls",
    status: "UPCOMING",
    capacity: 150,
    registeredCount: 112,
    registrationDeadline: "2026-10-15T23:59:59.000Z",
    isRegistrationOpen: true,
    registrationFee: 0,
    tags: ["Debate", "MUN", "Diplomacy", "Public Speaking"],
    requirements: ["Formal business attire", "Pre-assigned country position paper"],
    createdAt: "2026-08-25T00:00:00.000Z",
    updatedAt: "2026-08-25T00:00:00.000Z",
  },
  {
    id: "evt-cie-shark-tank",
    title: "Campus Shark Tank & Venture Pitch 2026",
    description: "Pitch your tech prototypes, mobile apps, or hardware ventures in front of angel investors, alumni entrepreneurs, and incubation partners.",
    eventType: "CLUB",
    category: "ENTREPRENEURSHIP",
    organizer: "CIE",
    organizerId: "club-cie",
    startDate: "2026-11-05",
    endDate: "2026-11-05",
    startTime: "10:00 AM",
    endTime: "04:30 PM",
    location: "Innovation Hub Seminar Hall (Block E)",
    status: "UPCOMING",
    capacity: 80,
    registeredCount: 45,
    registrationDeadline: "2026-10-28T23:59:59.000Z",
    isRegistrationOpen: true,
    registrationFee: 0,
    tags: ["Startup", "Pitch", "Funding", "Innovation"],
    requirements: ["Pitch deck in PDF/PPT", "Working prototype or demo video"],
    createdAt: "2026-08-28T00:00:00.000Z",
    updatedAt: "2026-08-28T00:00:00.000Z",
  },
  {
    id: "evt-came-shortfilm",
    title: "Frames & Reels: 48-Hour Filmmaking Festival",
    description: "Write, shoot, and edit an original 5-minute short film within 48 hours using the prompt disclosed at kickoff. Screenings and red-carpet awards.",
    eventType: "CLUB",
    category: "CULTURAL",
    organizer: "CAME",
    organizerId: "club-came",
    startDate: "2026-11-12",
    endDate: "2026-11-14",
    startTime: "05:00 PM",
    endTime: "08:00 PM",
    location: "Main Auditorium",
    status: "UPCOMING",
    capacity: 200,
    registeredCount: 140,
    registrationDeadline: "2026-11-08T23:59:59.000Z",
    isRegistrationOpen: true,
    registrationFee: 0,
    tags: ["Film", "Photography", "Theatrics", "Media"],
    requirements: ["Camera or smartphone", "Video editing software"],
    createdAt: "2026-08-30T00:00:00.000Z",
    updatedAt: "2026-08-30T00:00:00.000Z",
  },
  {
    id: "evt-nss-blood-donation",
    title: "Mega Campus Blood Donation Camp 2026",
    description: "Joint initiative with the Red Cross Blood Bank. Give the gift of life. Refreshments, donor certificates, and medical checkups provided.",
    eventType: "CLUB",
    category: "SOCIAL",
    organizer: "NSS",
    organizerId: "club-nss",
    startDate: "2026-10-08",
    endDate: "2026-10-08",
    startTime: "09:00 AM",
    endTime: "03:30 PM",
    location: "Student Activity Center (SAC Ground Floor)",
    status: "UPCOMING",
    capacity: 300,
    registeredCount: 215,
    registrationDeadline: "2026-10-07T18:00:00.000Z",
    isRegistrationOpen: true,
    registrationFee: 0,
    tags: ["Blood Donation", "Healthcare", "NSS", "Social Service"],
    requirements: ["Age 18+", "Minimum weight 45kg", "Proper breakfast before donating"],
    createdAt: "2026-08-18T00:00:00.000Z",
    updatedAt: "2026-08-18T00:00:00.000Z",
  },
  {
    id: "evt-college-annual-fest",
    title: "NexusFest 2026 — Annual Techno-Cultural Extravaganza",
    description: "The grand annual college festival featuring celebrity performances, battle of the bands, robotics arenas, esports tournaments, and cultural galas.",
    eventType: "CAMPUS",
    category: "FESTIVAL",
    organizer: "Dean of Student Affairs & Student Council",
    startDate: "2026-12-04",
    endDate: "2026-12-06",
    startTime: "10:00 AM",
    endTime: "10:00 PM",
    location: "Entire Campus Grounds & Open Air Theatre",
    status: "UPCOMING",
    capacity: 2500,
    registeredCount: 1420,
    registrationDeadline: "2026-11-30T23:59:59.000Z",
    isRegistrationOpen: true,
    registrationFee: 0,
    tags: ["College Fest", "Celebrity Night", "Cultural", "ProShow"],
    requirements: ["College ID Card mandatory for entry pass"],
    createdAt: "2026-08-01T00:00:00.000Z",
    updatedAt: "2026-08-01T00:00:00.000Z",
  },
  {
    id: "evt-sports-badminton-open",
    title: "Intramural Badminton Championship (Singles & Doubles)",
    description: "College-wide badminton tournament across Men's and Women's singles and doubles categories on synthetic indoor courts.",
    eventType: "SPORTS",
    category: "SPORTS",
    organizer: "Sports",
    organizerId: "club-sports",
    startDate: "2026-10-18",
    endDate: "2026-10-19",
    startTime: "09:00 AM",
    endTime: "06:00 PM",
    location: "Indoor Sports Complex — Courts 1-4",
    status: "UPCOMING",
    capacity: 64,
    registeredCount: 52,
    registrationDeadline: "2026-10-14T23:59:59.000Z",
    isRegistrationOpen: true,
    registrationFee: 0,
    tags: ["Badminton", "Intramural", "Indoor Sports"],
    requirements: ["Non-marking badminton shoes", "Own racquet (shuttlecocks provided)"],
    sportsMetadata: {
      sportName: "Badminton",
      fixtureType: "Single Elimination Knockout",
    },
    createdAt: "2026-08-22T00:00:00.000Z",
    updatedAt: "2026-08-22T00:00:00.000Z",
  },
  {
    id: "evt-apex-robowars",
    title: "Apex Robowars & Autonomous Maze Challenge 2026",
    description: "Battle of combat bots (15kg & 30kg category) along with autonomous line-following and maze-solver robot showcases.",
    eventType: "CLUB",
    category: "TECHNICAL",
    organizer: "Apex",
    organizerId: "club-apex",
    startDate: "2026-11-20",
    endDate: "2026-11-21",
    startTime: "10:00 AM",
    endTime: "05:30 PM",
    location: "Robotics Arena (SAC Complex)",
    status: "UPCOMING",
    capacity: 120,
    registeredCount: 88,
    registrationDeadline: "2026-11-15T23:59:59.000Z",
    isRegistrationOpen: true,
    registrationFee: 0,
    tags: ["Robotics", "Hardware", "Combat Bots", "Autonomous"],
    requirements: ["Safety goggles", "Bot specifications verification document"],
    createdAt: "2026-08-24T00:00:00.000Z",
    updatedAt: "2026-08-24T00:00:00.000Z",
  },
  {
    id: "evt-scope-icpc-sprint",
    title: "SCOPE CodeBlitz: ICPC-Style Team Programming Sprint",
    description: "3-person team contest solving 10 algorithmic challenges in 4 hours on private DOMjudge server with live scoreboard.",
    eventType: "CLUB",
    category: "TECHNICAL",
    organizer: "SCOPE",
    organizerId: "club-scope",
    startDate: "2026-10-28",
    endDate: "2026-10-28",
    startTime: "02:00 PM",
    endTime: "06:00 PM",
    location: "Computing Labs 2 & 3",
    status: "UPCOMING",
    capacity: 150,
    registeredCount: 110,
    registrationDeadline: "2026-10-25T23:59:59.000Z",
    isRegistrationOpen: true,
    registrationFee: 0,
    tags: ["Competitive Programming", "Algorithms", "ICPC", "Coding"],
    requirements: ["1 Laptop per team", "College ID cards"],
    createdAt: "2026-08-26T00:00:00.000Z",
    updatedAt: "2026-08-26T00:00:00.000Z",
  },
  {
    id: "evt-ewb-sustainability-summit",
    title: "Clean Campus & Renewable Energy Workshop",
    description: "Hands-on installation workshop for campus solar sensors, rainwater monitoring circuits, and green infrastructure.",
    eventType: "CLUB",
    category: "SOCIAL",
    organizer: "EWB",
    organizerId: "club-ewb",
    startDate: "2026-11-02",
    endDate: "2026-11-03",
    startTime: "10:00 AM",
    endTime: "04:00 PM",
    location: "Environmental Studies Lab & Rooftop Solar Array",
    status: "UPCOMING",
    capacity: 90,
    registeredCount: 65,
    registrationDeadline: "2026-10-30T23:59:59.000Z",
    isRegistrationOpen: true,
    registrationFee: 0,
    tags: ["Sustainability", "Solar", "Community", "Green Tech"],
    requirements: ["Notebook", "Enthusiasm for environmental solutions"],
    createdAt: "2026-08-27T00:00:00.000Z",
    updatedAt: "2026-08-27T00:00:00.000Z",
  },
];

// Authoritative Seed Memberships derived from Club Leaders (Role strictly LEADER)
export const SEED_MEMBERSHIPS: ClubMembership[] = SEED_CLUBS.flatMap((club) =>
  club.leaders.map((leader) => ({
    id: `mem-${club.id}-${leader.id}`,
    clubId: club.id,
    clubName: club.name,
    userId: leader.id,
    role: "LEADER" as const,
    joinedAt: "2024-01-01T00:00:00.000Z",
  }))
);

// ─── 3. Sports Activities & Facilities ────────────────────────────────────────

export const SEED_SPORTS_ACTIVITIES: SportsActivity[] = [
  {
    id: "sport-cricket",
    name: "Cricket",
    category: "OUTDOOR",
    venue: "Main Stadium Oval Ground (Turf Wickets & Practice Nets)",
    coachName: "Mr. Ramesh Kumar (BCCI Level 2 Coach)",
    practiceTimings: "06:00 AM – 08:00 AM & 04:30 PM – 06:30 PM",
    equipmentAvailable: true,
    captainName: "Karthik Reddy (4th Year)",
    captainContact: "Contact through Sports Council Desk",
    description: "Collegiate cricket squads with regular net practices, bowling machine training, and inter-university tournament participation.",
  },
  {
    id: "sport-badminton",
    name: "Badminton",
    category: "INDOOR",
    venue: "Indoor Sports Complex (4 Wooden & Synthetic Courts)",
    coachName: "Ms. Shalini Rao",
    practiceTimings: "06:30 AM – 08:30 AM & 04:30 PM – 07:30 PM",
    equipmentAvailable: true,
    captainName: "Pranav Varma (3rd Year)",
    captainContact: "Contact through Sports Council Desk",
    description: "Standard Yonex-grade indoor courts with dedicated morning fitness and evening sparring sessions.",
  },
  {
    id: "sport-basketball",
    name: "Basketball",
    category: "OUTDOOR",
    venue: "Floodlit Acrylic Basketball Courts 1 & 2",
    coachName: "Mr. David Victor",
    practiceTimings: "05:00 PM – 07:00 PM (Mon-Sat)",
    equipmentAvailable: true,
    captainName: "Samuel John (4th Year)",
    captainContact: "Contact through Sports Council Desk",
    description: "High-intensity collegiate squad competing in national university invitationals with daily tactical drills.",
  },
  {
    id: "sport-football",
    name: "Football",
    category: "OUTDOOR",
    venue: "Main Natural Turf Football Arena",
    coachName: "Mr. Abdul Razak",
    practiceTimings: "06:00 AM – 07:45 AM & 05:00 PM – 06:45 PM",
    equipmentAvailable: true,
    captainName: "Farhan Ali (3rd Year)",
    captainContact: "Contact through Sports Council Desk",
    description: "11-a-side regulation football ground with floodlights for evening training and friendly campus matches.",
  },
  {
    id: "sport-table-tennis",
    name: "Table Tennis",
    category: "INDOOR",
    venue: "Indoor Sports Complex — Mezzanine Floor",
    coachName: "Mr. K. Mahesh",
    practiceTimings: "04:30 PM – 07:30 PM (Daily)",
    equipmentAvailable: true,
    captainName: "Rituja Sen (3rd Year)",
    captainContact: "Contact through Sports Council Desk",
    description: "6 ITTF-approved Stag tables with automated ball feeder machines for training.",
  },
  {
    id: "sport-fitness-gym",
    name: "Gymnasium & Fitness Center",
    category: "FITNESS",
    venue: "Student Activity Center (SAC 1st Floor)",
    coachName: "Certified Fitness Trainer On-Duty",
    practiceTimings: "05:30 AM – 08:30 AM & 04:30 PM – 08:30 PM",
    equipmentAvailable: true,
    description: "State-of-the-art gym equipped with Olympic barbells, treadmills, elliptical trainers, cable machines, and power racks.",
  },
];

export const SEED_SPORTS_FACILITIES: SportsFacility[] = [
  {
    id: "fac-sports-complex",
    name: "Central Indoor Sports Complex",
    type: "Multi-Purpose Indoor Arena",
    timings: "06:00 AM – 08:30 PM",
    location: "Opposite Hostel Block B",
    amenities: ["4 Badminton Courts", "6 Table Tennis Tables", "Changing Rooms & Lockers", "Drinking Water Kiosks"],
    rules: ["Non-marking sports shoes mandatory", "Bring your own towel", "Entry only with valid College ID"],
  },
  {
    id: "fac-stadium-ground",
    name: "Main Athletics & Cricket Stadium",
    type: "Outdoor Stadium",
    timings: "05:30 AM – 07:00 PM",
    location: "North Campus Grounds",
    amenities: ["400m Running Track", "Turf Cricket Pitch", "Seating Pavilion for 1500", "Floodlight Towers"],
    rules: ["Spikes only permitted on running track", "No littering on turf", "Reservation needed for external matches"],
  },
];

export const SEED_SPORTS_TOURNAMENTS: SportsTournament[] = [
  {
    id: "tourn-cricket-2026",
    title: "Inter-Year T20 Cricket Championship",
    sport: "Cricket",
    dateRange: "Oct 4 – Oct 25, 2026",
    venue: "Main Stadium",
    eligibility: "Open to all enrolled students (4 squads: 1st, 2nd, 3rd, 4th Year)",
    registrationDeadline: "2026-09-30T23:59:59.000Z",
    isOpenForRegistration: true,
    contactPerson: "Sports Council Secretary (Room 104 SAC)",
  },
  {
    id: "tourn-badminton-2026",
    title: "CampusNexus Badminton Singles Open",
    sport: "Badminton",
    dateRange: "Oct 18 – Oct 19, 2026",
    venue: "Indoor Sports Complex",
    eligibility: "Open to all students across all branches",
    registrationDeadline: "2026-10-14T23:59:59.000Z",
    isOpenForRegistration: true,
    contactPerson: "Badminton Captain (Pranav Varma)",
  },
];

// ─── 4. Campus Facilities ─────────────────────────────────────────────────────

export const SEED_FACILITIES: CampusFacility[] = [
  {
    id: "fac-central-library",
    name: "Central Library & Digital Knowledge Hub",
    category: "ACADEMIC",
    description: "Four-story modern library housing over 75,000 volumes, IEEE/ACM digital access terminals, sound-proof research cubicles, and 24/7 reading halls.",
    location: "Block-L (Central Academic Quad)",
    operatingHours: "08:00 AM – 10:00 PM (Extended during exam periods to 24/7)",
    services: [
      "Book Lending & Returns",
      "Digital Library & E-Journal Access",
      "Quiet Study Cubicles",
      "Reprography & Printing Station",
      "Discussion Rooms for Study Groups",
    ],
    inChargeName: "Dr. K. V. Raman (Chief Librarian)",
    contactEmail: "library.helpdesk@campusnexus.edu",
    contactPhone: "Ext. 2401",
    capacity: 800,
    guidelines: [
      "Maintain absolute silence in study zones",
      "Barcode scanning required for borrowing",
      "Bag deposits at entrance lockers",
    ],
  },
  {
    id: "fac-computing-center",
    name: "Advanced Computing & Cloud Innovation Lab",
    category: "ACADEMIC",
    description: "State-of-the-art computing facility with 450 high-performance workstations, GPU clusters for AI/ML workloads, and high-speed gigabit fiber backbone.",
    location: "Block-C, 2nd & 3rd Floors",
    operatingHours: "08:30 AM – 08:30 PM (Mon-Sat)",
    services: [
      "High-Performance Computing (HPC) & GPU Access",
      "Linux & Open Source Workstations",
      "Cloud Virtual Lab Environments",
      "Campus Competitive Coding Host Servers",
    ],
    inChargeName: "Prof. N. Srinivas Rao (System Administrator)",
    contactEmail: "ccf.admin@campusnexus.edu",
    contactPhone: "Ext. 3105",
    capacity: 450,
    guidelines: [
      "Valid LDAP student credentials required to login",
      "No food or beverages allowed inside lab suites",
    ],
  },
  {
    id: "fac-main-auditorium",
    name: "Main Campus Auditorium",
    category: "AUDITORIUM",
    description: "Acoustically treated multi-tier auditorium featuring 4K projection, professional line-array sound systems, and motorized stage lighting for collegiate events.",
    location: "Block-A, Main Entrance Quadrangle",
    operatingHours: "09:00 AM – 09:00 PM (Event dependent)",
    services: [
      "National Conferences & Seminars",
      "Placement Drive Keynotes & Pre-Placement Talks",
      "Cultural & Theatrical Stage Productions",
      "Annual Convocation & Freshers Welcomes",
    ],
    inChargeName: "Auditorium Management Committee",
    contactEmail: "auditorium.booking@campusnexus.edu",
    contactPhone: "Ext. 1102",
    capacity: 1200,
  },
  {
    id: "fac-health-center",
    name: "Campus Health & Medical Center",
    category: "HEALTHCARE",
    description: "Full-time campus medical dispensary with on-duty resident doctors, nurses, basic pathology testing, emergency first-aid beds, and a dedicated ambulance.",
    location: "Near Residential Quarters & Block A Hostel",
    operatingHours: "24 Hours (Doctors available 09:00 AM – 07:00 PM; On-call 24/7)",
    services: [
      "General Medical Consultation",
      "Emergency First-Aid & Triage",
      "Free Essential Medication Dispensary",
      "24/7 Emergency Ambulance Service",
      "Annual Student Health & Eye Checkups",
    ],
    inChargeName: "Dr. Pratibha Sharma (Chief Medical Officer)",
    contactEmail: "healthcenter@campusnexus.edu",
    contactPhone: "Emergency: Ext. 9999 / Ambulance Direct",
    capacity: 12,
  },
  {
    id: "fac-student-center",
    name: "Student Activity Center (SAC)",
    category: "STUDENT_CENTER",
    description: "The vibrant heart of campus life housing student club office rooms, multi-purpose practice studios, common relaxation lounges, and stationery store.",
    location: "SAC Building (Between Academic Blocks and Hostels)",
    operatingHours: "07:00 AM – 09:30 PM (Daily)",
    services: [
      "Club Operations & Meeting Rooms",
      "Dance & Music Practice Studio",
      "Student Council Office",
      "Stationery, Xerox & Project Binding Store",
      "Lost & Found Central Desk",
    ],
    inChargeName: "Dean of Student Affairs Office",
    contactEmail: "sac.admin@campusnexus.edu",
    contactPhone: "Ext. 4001",
    capacity: 600,
  },
  {
    id: "fac-admin-block",
    name: "Administrative Central Complex",
    category: "ADMINISTRATION",
    description: "Houses the Principal's Secretariat, Registrar Office, Academic Section, Examination Cell, Accounts & Fee Counter, and Placement Operations Center.",
    location: "Administrative Block (Building 1)",
    operatingHours: "09:30 AM – 04:30 PM (Mon-Fri) & 09:30 AM – 01:00 PM (Sat)",
    services: [
      "Tuition & Exam Fee Processing",
      "Bonafide & Transcript Certificates",
      "Scholarship Verification Desk",
      "Admissions & Identity Card Section",
    ],
    inChargeName: "Office of the Registrar",
    contactEmail: "admin.office@campusnexus.edu",
    contactPhone: "Ext. 1001",
  },
];

// ─── 5. Lost & Found Seed Items ───────────────────────────────────────────────

export const SEED_LOST_FOUND: LostFoundItem[] = [
  {
    id: "lf-001",
    title: "HP Blue Wireless Mouse found in Central Lab 3",
    description: "Found an HP wireless mouse with USB nano receiver left on workstation PC-42 on Friday evening.",
    type: "FOUND",
    category: "ELECTRONICS",
    location: "Central Computing Facility (Lab 3)",
    incidentDate: "2026-09-08",
    status: "OPEN",
    contactName: "Lab Assistant (Mr. Ramesh)",
    contactNote: "Deposited with CCF Lab Assistant Desk. Bring your student ID to verify.",
    authorId: "usr-student-cse-1",
    authorName: "Rahul Sharma",
    authorDepartment: "Computer Science",
    createdAt: "2026-09-08T16:30:00.000Z",
    updatedAt: "2026-09-08T16:30:00.000Z",
  },
  {
    id: "lf-002",
    title: "Lost Black Fastrack Leather Wallet near SAC Cafeteria",
    description: "Contains college ID card, driving license, and hostel mess card. If found, please contact or submit at SAC desk.",
    type: "LOST",
    category: "BAGS_WALLETS",
    location: "SAC Courtyard / Garden Benches",
    incidentDate: "2026-09-09",
    status: "OPEN",
    contactName: "Vikas Reddy",
    contactNote: "Please hand over to SAC Room 101 or contact via CampusNexus in-app message.",
    authorId: "usr-student-ece-1",
    authorName: "Vikas Reddy",
    authorDepartment: "Electronics & Communication",
    createdAt: "2026-09-09T11:15:00.000Z",
    updatedAt: "2026-09-09T11:15:00.000Z",
  },
  {
    id: "lf-003",
    title: "Found Casio fx-991EX Scientific Calculator in Library 2nd Floor",
    description: "Scientific calculator with 'K.T' written on the back cover found on reading table #18.",
    type: "FOUND",
    category: "ELECTRONICS",
    location: "Central Library (2nd Floor Reading Hall)",
    incidentDate: "2026-09-07",
    status: "OPEN",
    contactName: "Library Helpdesk Counter",
    contactNote: "Submitted at Central Library Circulation Counter. Claim by showing registration number.",
    authorId: "usr-student-it-1",
    authorName: "Pooja Hegde",
    authorDepartment: "Information Technology",
    createdAt: "2026-09-07T14:00:00.000Z",
    updatedAt: "2026-09-07T14:00:00.000Z",
  },
  {
    id: "lf-004",
    title: "Lost Set of Room Keys with Marvel Keychain",
    description: "Bunch of 2 brass keys with an Iron Man metal keychain lost between Block B Hostel and Cricket Ground.",
    type: "LOST",
    category: "KEYS",
    location: "Pathway between Hostel Block B & Ground",
    incidentDate: "2026-09-06",
    status: "RESOLVED",
    contactName: "Aditya Nambiar",
    contactNote: "Claimed and recovered from Security Gate #2.",
    authorId: "usr-student-cse-2",
    authorName: "Aditya Nambiar",
    authorDepartment: "Computer Science",
    createdAt: "2026-09-06T18:00:00.000Z",
    updatedAt: "2026-09-07T10:00:00.000Z",
  },
];

// ─── 6. Campus Marketplace Seed Listings ──────────────────────────────────────

export const SEED_MARKETPLACE: MarketplaceListing[] = [
  {
    id: "mkt-001",
    title: "Casio fx-991CW ClassWiz Scientific Calculator (Brand New)",
    description: "Original Casio fx-991CW with high-resolution 4-gradation display. Purchased last semester, barely used. Original box & warranty card included.",
    category: "CALCULATORS",
    price: 950,
    isNegotiable: true,
    condition: "LIKE_NEW",
    status: "AVAILABLE",
    sellerId: "usr-student-ece-1",
    sellerName: "Vikas Reddy",
    sellerDepartment: "Electronics & Communication",
    sellerContactNote: "Available for hand-to-hand exchange at Central Library or SAC. Contact via in-app message.",
    createdAt: "2026-09-08T10:00:00.000Z",
    updatedAt: "2026-09-08T10:00:00.000Z",
  },
  {
    id: "mkt-002",
    title: "Complete 3rd Year CSE Textbook Bundle (Database Systems + OS + Networks)",
    description: "Standard textbooks: Navathe (DBMS), Galvin (Operating Systems), and Tanenbaum (Computer Networks). Clean, unmarked pages with sticky tab highlights.",
    category: "TEXTBOOKS",
    price: 1200,
    isNegotiable: false,
    condition: "GOOD",
    status: "AVAILABLE",
    sellerId: "usr-student-cse-1",
    sellerName: "Rahul Sharma",
    sellerDepartment: "Computer Science",
    sellerContactNote: "Can deliver anywhere on campus or hostel blocks. Send in-app message.",
    createdAt: "2026-09-09T09:30:00.000Z",
    updatedAt: "2026-09-09T09:30:00.000Z",
  },
  {
    id: "mkt-003",
    title: "Engineering Drawing Board + Mini Drafter + T-Scale Set",
    description: "Full first-year mechanical engineering drawing set with heavy-duty Omega mini-drafter, sheet clips, and durable carrying bag.",
    category: "DRAWING_TOOLS",
    price: 650,
    isNegotiable: true,
    condition: "GOOD",
    status: "AVAILABLE",
    sellerId: "usr-student-mech-1",
    sellerName: "Aarav Sharma",
    sellerDepartment: "Mechanical Engineering",
    sellerContactNote: "Meet at Mech Lab Ground Floor or Hostel Block A.",
    createdAt: "2026-09-07T15:00:00.000Z",
    updatedAt: "2026-09-07T15:00:00.000Z",
  },
  {
    id: "mkt-004",
    title: "Hero Sprint 21-Speed Gear Bicycle (Well Maintained)",
    description: "Sturdy aluminum alloy frame with front suspension, dual disc brakes, and new tires. Ideal for daily hostel-to-campus commuting.",
    category: "BICYCLES",
    price: 3800,
    isNegotiable: true,
    condition: "GOOD",
    status: "AVAILABLE",
    sellerId: "usr-student-civil-1",
    sellerName: "Suresh Babu",
    sellerDepartment: "Civil Engineering",
    sellerContactNote: "Test ride available at Hostel Block C parking area.",
    createdAt: "2026-09-05T12:00:00.000Z",
    updatedAt: "2026-09-05T12:00:00.000Z",
  },
  {
    id: "mkt-005",
    title: "Hostel Study Lamp (Rechargeable LED with 3 Warmth Modes)",
    description: "Rechargeable desk lamp with touch brightness controls and USB-C fast charging. Battery lasts 8+ hours on single charge.",
    category: "ROOM_ESSENTIALS",
    price: 400,
    isNegotiable: false,
    condition: "LIKE_NEW",
    status: "SOLD",
    sellerId: "usr-student-it-1",
    sellerName: "Pooja Hegde",
    sellerDepartment: "Information Technology",
    sellerContactNote: "Sold to hostel resident.",
    createdAt: "2026-09-02T10:00:00.000Z",
    updatedAt: "2026-09-04T18:00:00.000Z",
  },
];

// ─── 7. Transport Routes & Schedules ──────────────────────────────────────────

export const SEED_TRANSPORT: TransportRoute[] = [
  {
    id: "route-01",
    routeNumber: "Route 1",
    routeName: "Secunderabad Station – Campus Expressway",
    driverName: "Mr. G. Narsing Rao",
    driverPhone: "Available at Transport Office",
    busNumber: "TS 08 UB 4512",
    capacity: 55,
    operatingDays: "Monday to Saturday",
    feePerSemester: 14000,
    inChargeContact: "Transport Helpdesk Ext. 1801",
    stops: [
      { stopName: "Secunderabad Railway Station (Clock Tower)", morningPickupTime: "07:15 AM", eveningDropTime: "06:15 PM", landmark: "Opposite Gurudwara" },
      { stopName: "Paradise Circle", morningPickupTime: "07:25 AM", eveningDropTime: "06:05 PM", landmark: "Paradise Metro Pillar 18" },
      { stopName: "Tadbund X Roads", morningPickupTime: "07:35 AM", eveningDropTime: "05:55 PM", landmark: "Hanuman Temple" },
      { stopName: "Bowenpally Checkpost", morningPickupTime: "07:45 AM", eveningDropTime: "05:45 PM", landmark: "Dairy Farm Road" },
      { stopName: "Suchitra Junction", morningPickupTime: "07:55 AM", eveningDropTime: "05:35 PM", landmark: "Metro Pillar / Flyover" },
      { stopName: "Kompally Big Bazaar", morningPickupTime: "08:10 AM", eveningDropTime: "05:20 PM", landmark: "Cineplanet Mall" },
      { stopName: "CampusNexus Main Gate", morningPickupTime: "08:35 AM", eveningDropTime: "04:50 PM", landmark: "Terminal Point" },
    ],
  },
  {
    id: "route-02",
    routeNumber: "Route 2",
    routeName: "Kukatpally / KPHB – JNTU – Campus",
    driverName: "Mr. M. Yadagiri",
    driverPhone: "Available at Transport Office",
    busNumber: "TS 08 UB 4518",
    capacity: 55,
    operatingDays: "Monday to Saturday",
    feePerSemester: 14000,
    inChargeContact: "Transport Helpdesk Ext. 1801",
    stops: [
      { stopName: "KPHB Colony Phase 1", morningPickupTime: "07:20 AM", eveningDropTime: "06:10 PM", landmark: "Beside Temple Bus Stop" },
      { stopName: "JNTU Main Gate", morningPickupTime: "07:30 AM", eveningDropTime: "06:00 PM", landmark: "Metro Station Exit B" },
      { stopName: "Miyapur X Roads", morningPickupTime: "07:45 AM", eveningDropTime: "05:45 PM", landmark: "Allwyn Colony Arch" },
      { stopName: "Bachupally Junction", morningPickupTime: "08:00 AM", eveningDropTime: "05:30 PM", landmark: "Silver Oaks Cross" },
      { stopName: "Gandimaisamma X Roads", morningPickupTime: "08:15 AM", eveningDropTime: "05:15 PM", landmark: "Police Station" },
      { stopName: "CampusNexus Main Gate", morningPickupTime: "08:35 AM", eveningDropTime: "04:50 PM", landmark: "Terminal Point" },
    ],
  },
  {
    id: "route-03",
    routeNumber: "Route 3",
    routeName: "ECIL – Dilsukhnagar – Uppal – Campus",
    driverName: "Mr. K. Mallesh",
    driverPhone: "Available at Transport Office",
    busNumber: "TS 08 UB 4524",
    capacity: 55,
    operatingDays: "Monday to Saturday",
    feePerSemester: 15500,
    inChargeContact: "Transport Helpdesk Ext. 1801",
    stops: [
      { stopName: "Dilsukhnagar Metro", morningPickupTime: "07:05 AM", eveningDropTime: "06:30 PM", landmark: "Sai Baba Temple" },
      { stopName: "Uppal Ring Road", morningPickupTime: "07:25 AM", eveningDropTime: "06:10 PM", landmark: "Metro Pillar 42" },
      { stopName: "ECIL X Roads", morningPickupTime: "07:40 AM", eveningDropTime: "05:55 PM", landmark: "Radhika Theatre" },
      { stopName: "Sainikpuri / Yapral", morningPickupTime: "07:55 AM", eveningDropTime: "05:40 PM", landmark: "Vayupuri Cross" },
      { stopName: "Alwal IG Statue", morningPickupTime: "08:10 AM", eveningDropTime: "05:25 PM", landmark: "Alwal Circle" },
      { stopName: "CampusNexus Main Gate", morningPickupTime: "08:35 AM", eveningDropTime: "04:50 PM", landmark: "Terminal Point" },
    ],
  },
  {
    id: "route-shuttle",
    routeNumber: "Campus Shuttle",
    routeName: "Hostel – Sports Complex – Academic Blocks Ring",
    driverName: "Campus Internal Transport Staff",
    driverPhone: "Available at SAC Desk",
    busNumber: "Electric Shuttle EV-01",
    capacity: 30,
    operatingDays: "All 7 Days (Every 20 mins during peak hours)",
    feePerSemester: 0,
    inChargeContact: "SAC Helpdesk Ext. 4001",
    stops: [
      { stopName: "Hostel Blocks A/B/C Quad", morningPickupTime: "Continuous Loop", eveningDropTime: "Continuous Loop", landmark: "Mess Entrance" },
      { stopName: "Girls Hostel Blocks D/E", morningPickupTime: "Continuous Loop", eveningDropTime: "Continuous Loop", landmark: "Security Gate" },
      { stopName: "Indoor Sports Complex & Ground", morningPickupTime: "Continuous Loop", eveningDropTime: "Continuous Loop", landmark: "Stadium Pavilion" },
      { stopName: "Student Activity Center (SAC)", morningPickupTime: "Continuous Loop", eveningDropTime: "Continuous Loop", landmark: "Central Courtyard" },
      { stopName: "Academic Blocks A, B, C & Central Library", morningPickupTime: "Continuous Loop", eveningDropTime: "Continuous Loop", landmark: "Main Flagpost" },
    ],
  },
];

// ─── 8. Hostel Information ───────────────────────────────────────────────────

export const SEED_HOSTEL_INFO: HostelInfo = {
  blocks: [
    {
      id: "block-a",
      name: "Aryabhatta Hall (Block A)",
      gender: "BOYS",
      capacity: 450,
      floors: 5,
      wardenName: "Dr. P. Venkatesh (Associate Professor)",
      wardenContact: "Contact via Hostel Warden Office",
      wardenEmail: "warden.blocka@campusnexus.edu",
      amenities: [
        "High-Speed Wi-Fi (100 Mbps)",
        "Solar Water Heaters on All Floors",
        "Air-Conditioned Study Lounge (Ground Floor)",
        "Water Coolers with UV-Purification",
        "Automated Coin Laundry & Ironing Hub",
        "24/7 CCTV & Security Guard Coverage",
      ],
      description: "Dedicated residential block for 3rd and 4th-year engineering students with single and double occupancy rooms.",
    },
    {
      id: "block-b",
      name: "Bhaskara Hall (Block B)",
      gender: "BOYS",
      capacity: 500,
      floors: 5,
      wardenName: "Prof. K. Satyanarayana",
      wardenContact: "Contact via Hostel Warden Office",
      wardenEmail: "warden.blockb@campusnexus.edu",
      amenities: [
        "High-Speed Wi-Fi Backbone",
        "Indoor Recreation Area (Table Tennis & Chess)",
        "Purified Drinking Water Dispensers",
        "Dedicated Power Backup Generators",
        "Common Room with LED Television",
      ],
      description: "Junior boys hostel for 1st and 2nd-year undergraduate students with 3-sharing spacious ventilated rooms.",
    },
    {
      id: "block-c",
      name: "Chanakya Hall (Block C)",
      gender: "BOYS",
      capacity: 350,
      floors: 4,
      wardenName: "Dr. B. Sudhakar",
      wardenContact: "Contact via Hostel Warden Office",
      wardenEmail: "warden.blockc@campusnexus.edu",
      amenities: [
        "Quiet Reading and Project Rooms",
        "Attached Washroom Options",
        "24/7 Hot Water Facility",
        "Laundry Service Delivery Point",
      ],
      description: "Postgraduate scholars and senior undergraduate students residential wing.",
    },
    {
      id: "block-d",
      name: "Gargi Hall (Block D)",
      gender: "GIRLS",
      capacity: 480,
      floors: 5,
      wardenName: "Dr. M. Sangeetha (Chief Women's Warden)",
      wardenContact: "Contact via Hostel Warden Office",
      wardenEmail: "warden.gargi@campusnexus.edu",
      amenities: [
        "High-Speed Wi-Fi & LAN ports",
        "Dedicated Gym & Yoga Room inside Block",
        "Doctor on Call & 24/7 Resident Nurse",
        "Biometric Turnstile Access Control",
        "Air-Conditioned Study Library & Discussion Cubicles",
        "Nutritious Multi-Cuisine Mess Hall",
      ],
      description: "Premier women's residential hall for senior undergraduate and postgraduate students with high security.",
    },
    {
      id: "block-e",
      name: "Maitreyi Hall (Block E)",
      gender: "GIRLS",
      capacity: 420,
      floors: 5,
      wardenName: "Mrs. V. Lakshmi Devi",
      wardenContact: "Contact via Hostel Warden Office",
      wardenEmail: "warden.maitreyi@campusnexus.edu",
      amenities: [
        "High-Speed Wi-Fi",
        "Badminton Courtyard inside Premises",
        "UV Drinking Water Stations",
        "Round-the-clock Female Security Guards",
        "Modern Dining Hall & Cafeteria Access",
      ],
      description: "Freshmen and sophomore women's residential hall designed with secure courtyards and dedicated study rooms.",
    },
  ],
  generalAmenities: [
    "Centrally Managed Multi-Cuisine Mess (Veg & Non-Veg 4 times/week)",
    "High-Speed Campus Optical Fiber Network & Wi-Fi",
    "24/7 Power Backup with Dual Industrial Generators",
    "On-Campus Health Center with Ambulance Services",
    "Biometric & RFID Security Access Systems",
    "Automated Water Purification & Solar Water Heating",
    "Dedicated Maintenance & Plumbing Response Cell",
  ],
  messTimings: {
    breakfast: "07:30 AM – 09:00 AM",
    lunch: "12:15 PM – 02:00 PM",
    snacks: "04:45 PM – 05:45 PM",
    dinner: "07:30 PM – 09:15 PM",
  },
  rulesAndGuidelines: [
    "Entry gates close at 09:00 PM sharp; late entries require prior warden permission",
    "College ID cards must be carried at all times for dining hall and gate verification",
    "Cooking appliances, induction heaters, and high-power irons strictly prohibited in rooms",
    "Quiet hours observed from 11:00 PM to 06:00 AM daily",
    "Guests and day scholars not permitted inside residential corridors without passes",
  ],
  chiefWarden: {
    name: "Dr. K. Prabhakar Rao (Chief Warden & Professor)",
    office: "Central Hostel Administration Office (Ground Floor, Block A)",
    contact: "Ext. 5001 / Direct Office Desk",
    email: "chief.warden@campusnexus.edu",
  },
};

// ─── 9. Campus Directory ──────────────────────────────────────────────────────

export const SEED_DIRECTORY: CampusDirectoryEntry[] = [
  {
    id: "dir-01",
    officeName: "Office of the Principal / Director",
    category: "ADMINISTRATION",
    headName: "Dr. V. Ravindranathan",
    designation: "Principal & Director",
    location: "Administrative Block, 1st Floor (Room 101)",
    operatingHours: "09:30 AM – 05:00 PM (Mon-Sat)",
    contactNumber: "Ext. 1001",
    email: "principal@campusnexus.edu",
    servicesProvided: ["Institutional Governance", "Academic Policy Approvals", "Official Representations"],
  },
  {
    id: "dir-02",
    officeName: "Dean of Student Affairs (DSA)",
    category: "STUDENT_AFFAIRS",
    headName: "Dr. S. K. Murthy",
    designation: "Dean of Student Welfare & Affairs",
    location: "Student Activity Center (SAC 2nd Floor)",
    operatingHours: "09:30 AM – 05:00 PM (Mon-Sat)",
    contactNumber: "Ext. 4001",
    email: "dsa@campusnexus.edu",
    servicesProvided: ["Club Approvals & Funding", "Cultural Festival Operations", "Student Discipline & Grievances", "Anti-Ragging Cell"],
  },
  {
    id: "dir-03",
    officeName: "Controller of Examinations (CoE)",
    category: "EXAMINATION",
    headName: "Dr. M. S. Ramachandran",
    designation: "Controller of Examinations",
    location: "Administrative Block, Ground Floor (Room 108)",
    operatingHours: "10:00 AM – 04:30 PM (Mon-Fri)",
    contactNumber: "Ext. 1205",
    email: "coe@campusnexus.edu",
    servicesProvided: ["Semester Exam Schedules", "Hall Ticket Issuance", "Grade Cards & Transcripts", "Revaluation & Recounting"],
  },
  {
    id: "dir-04",
    officeName: "Training & Placement Cell (T&P)",
    category: "STUDENT_AFFAIRS",
    headName: "Prof. Anant Deshmukh",
    designation: "Head — Corporate Relations & Placements",
    location: "Placement Center (Block-E 1st Floor)",
    operatingHours: "09:00 AM – 06:00 PM (Mon-Sat)",
    contactNumber: "Ext. 3501",
    email: "placements@campusnexus.edu",
    servicesProvided: ["Campus Recruitment Drives", "Internship Opportunities", "Mock Interviews & Soft Skills", "Alumni Connect"],
  },
  {
    id: "dir-05",
    officeName: "Academic Section & Registrar Office",
    category: "ACADEMIC_OFFICE",
    headName: "Mr. B. N. Sastry",
    designation: "Assistant Registrar (Academics)",
    location: "Administrative Block, Room 104",
    operatingHours: "10:00 AM – 04:00 PM (Mon-Fri)",
    contactNumber: "Ext. 1005",
    email: "academics@campusnexus.edu",
    servicesProvided: ["Bonafide Certificates", "Original Degree Document Verification", "Scholarship Forwarding", "Course Registrations"],
  },
  {
    id: "dir-06",
    officeName: "IT Services & Network Operations Center (NOC)",
    category: "IT_SERVICES",
    headName: "Prof. N. Srinivas Rao",
    designation: "Head — IT & Systems Infrastructure",
    location: "Block-C, Ground Floor (Room C-04)",
    operatingHours: "08:30 AM – 08:00 PM (Mon-Sat)",
    contactNumber: "Ext. 3101",
    email: "itsupport@campusnexus.edu",
    servicesProvided: ["LDAP / College Email Credentials", "Campus Wi-Fi Access Tokens", "Laboratory Software Licensing", "Portal Troubleshooting"],
  },
  {
    id: "dir-07",
    officeName: "Campus Security & Emergency Response Desk",
    category: "EMERGENCY",
    headName: "Major (Retd.) K. R. Yadav",
    designation: "Chief Security Officer",
    location: "Main Security Gate #1",
    operatingHours: "24 Hours (Daily)",
    contactNumber: "Direct: 040-23459999 / Ext. 9999",
    email: "security@campusnexus.edu",
    servicesProvided: ["Emergency Security Dispatch", "Gate Passes & Vehicle Registrations", "CCTV Surveillance Room", "Campus Lost Property Custody"],
  },
  {
    id: "dir-08",
    officeName: "Campus Health & Ambulance Dispatch",
    category: "EMERGENCY",
    headName: "Dr. Pratibha Sharma",
    designation: "Chief Medical Officer",
    location: "Campus Health Center",
    operatingHours: "24 Hours (Daily)",
    contactNumber: "Emergency: Ext. 9111",
    email: "healthcenter@campusnexus.edu",
    servicesProvided: ["Emergency Medical Response", "Ambulance Callout", "First-Aid Triage"],
  },
];
