# Development Profile Configuration
spring:
  jpa:
    show-sql: true

logging:
  level:
    root: INFO
    com.campusnexus: DEBUG
    org.springframework.web: INFO
    org.flywaydb: INFO
    org.springframework.jdbc: INFO
    org.hibernate.SQL: DEBUG

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}


