import {
  PlacementOpportunity,
  InternshipOpportunity,
  ResumeReviewRequest,
  SmartCollection,
  StudentCareerProfile,
} from "@/types/career.types";

// ─── Deterministic Seed Placements ───────────────────────────────────────────

export const SEED_PLACEMENTS: PlacementOpportunity[] = [
  {
    id: "place-101",
    type: "PLACEMENT",
    companyName: "Google",
    companyLogo: "/companies/google.png",
    companyWebsite: "https://careers.google.com",
    role: "Software Development Engineer (SDE-1)",
    domain: "Software Engineering",
    description:
      "Join Google's Core Infrastructure engineering team in Hyderabad. You will build highly scalable distributed systems, optimize query processing pipelines, and build world-class web services serving billions of users worldwide.",
    responsibilities: [
      "Design and implement scalable backend microservices and APIs in Java/C++.",
      "Collaborate with multi-disciplinary teams across distributed system architectures.",
      "Optimize data structures, memory footprints, and low-latency network protocols.",
      "Write unit, integration, and performance benchmarking suites.",
    ],
    packageLpa: 24.0,
    packageDetails: "₹24.0 LPA (Base: ₹18 LPA + Performance Bonus: ₹3 LPA + Stocks: ₹3 LPA)",
    location: "Hyderabad, Telangana",
    workMode: "HYBRID",
    requiredSkills: ["Data Structures & Algorithms", "Java", "C++", "System Design", "Operating Systems", "SQL"],
    eligibility: {
      eligibleDepartments: ["cse", "it"],
      eligibleYears: [4],
      minCgpa: 8.0,
      maxBacklogs: 0,
      requiredSkills: ["Data Structures", "Algorithms", "Java"],
      graduationYear: "2025",
    },
    applicationDeadline: "2026-10-15T23:59:59Z",
    driveDate: "2026-10-22T09:00:00Z",
    selectionRounds: [
      "Online Coding Assessment (3 DSA Problems, 90 mins)",
      "Technical Interview 1 (Data Structures & Problem Solving)",
      "Technical Interview 2 (System Design & Core CS Fundamentals)",
      "Googleyness & Leadership Fit Round",
    ],
    applicationMethod: "DIRECT",
    status: "PUBLISHED",
    applicantsCount: 42,
    createdBy: "user-admin-001",
    createdAt: "2026-09-01T10:00:00Z",
    updatedAt: "2026-09-01T10:00:00Z",
  },
  {
    id: "place-102",
    type: "PLACEMENT",
    companyName: "Qualcomm",
    companyLogo: "/companies/qualcomm.png",
    companyWebsite: "https://www.qualcomm.com/company/careers",
    role: "Embedded Software Engineer",
    domain: "Embedded Systems & Hardware",
    description:
      "Qualcomm Wireless R&D Center is seeking talented electronics and systems engineers to develop next-generation modem firmware, RTOS drivers, and low-level kernel abstractions for Snapdragon mobile and automotive platforms.",
    responsibilities: [
      "Develop embedded C/C++ firmware for ARM Cortex and DSP micro-architectures.",
      "Design and debug board support packages (BSP), I2C, SPI, and PCIe peripheral device drivers.",
      "Profile and optimize memory constraints, cache coherence, and power management loops.",
      "Perform hardware-software co-simulation using oscilloscopes, logic analyzers, and JTAG.",
    ],
    packageLpa: 16.5,
    packageDetails: "₹16.5 LPA (Fixed: ₹14 LPA + Joining Bonus: ₹1.5 LPA + Performance: ₹1 LPA)",
    location: "Hyderabad, Telangana",
    workMode: "ONSITE",
    requiredSkills: ["Embedded C", "C++", "Microcontrollers", "RTOS", "Computer Architecture", "Linux Device Drivers"],
    eligibility: {
      eligibleDepartments: ["ece", "eee"],
      eligibleYears: [4],
      minCgpa: 7.5,
      maxBacklogs: 0,
      requiredSkills: ["Embedded C", "Microcontrollers"],
      graduationYear: "2025",
    },
    applicationDeadline: "2026-10-18T23:59:59Z",
    driveDate: "2026-10-25T09:30:00Z",
    selectionRounds: [
      "Technical Aptitude & Embedded C Online Assessment",
      "Core Electronics & Microcontroller Architecture Interview",
      "Low-level Programming & Firmware Debugging Round",
      "HR & Managerial Round",
    ],
    applicationMethod: "DIRECT",
    status: "PUBLISHED",
    applicantsCount: 28,
    createdBy: "user-admin-001",
    createdAt: "2026-09-02T11:00:00Z",
    updatedAt: "2026-09-02T11:00:00Z",
  },
  {
    id: "place-103",
    type: "PLACEMENT",
    companyName: "Microsoft",
    companyLogo: "/companies/microsoft.png",
    companyWebsite: "https://careers.microsoft.com",
    role: "Cloud & AI Solutions Engineer",
    domain: "Cloud & AI",
    description:
      "Design scalable enterprise cloud native microservices on Azure. Work on container orchestration, large language model deployment pipelines, and mission-critical cloud telemetry.",
    responsibilities: [
      "Architect resilient cloud services using Azure SDKs, C# / .NET Core, and Python.",
      "Automate CI/CD deployment pipelines using GitHub Actions and Kubernetes.",
      "Build real-time monitoring, telemetry, and observability frameworks.",
      "Participate in agile sprints, architectural reviews, and code refactoring.",
    ],
    packageLpa: 21.5,
    packageDetails: "₹21.5 LPA (Base: ₹16 LPA + Retirals: ₹1.5 LPA + Stock Grant: ₹4 LPA)",
    location: "Hyderabad, Telangana",
    workMode: "HYBRID",
    requiredSkills: ["C#", "Python", "Cloud Architecture", "Docker", "Kubernetes", "Data Structures", "SQL"],
    eligibility: {
      eligibleDepartments: ["cse", "it", "ece"],
      eligibleYears: [4],
      minCgpa: 7.5,
      maxBacklogs: 0,
      graduationYear: "2025",
    },
    applicationDeadline: "2026-10-20T23:59:59Z",
    driveDate: "2026-10-28T10:00:00Z",
    selectionRounds: [
      "Codility Online Assessment (Algorithms + System Analysis)",
      "Technical Round 1: DSA & Object-Oriented Design",
      "Technical Round 2: Cloud Systems & DB Optimization",
      "AA (As Appropriate) Leadership Round",
    ],
    applicationMethod: "DIRECT",
    status: "PUBLISHED",
    applicantsCount: 56,
    createdBy: "user-admin-001",
    createdAt: "2026-09-03T09:30:00Z",
    updatedAt: "2026-09-03T09:30:00Z",
  },
  {
    id: "place-104",
    type: "PLACEMENT",
    companyName: "Deloitte",
    companyLogo: "/companies/deloitte.png",
    companyWebsite: "https://www2.deloitte.com/in/en/careers",
    role: "Technology Consulting Analyst",
    domain: "Consulting & Analytics",
    description:
      "Campus-wide recruitment for analytical problem-solvers across all engineering branches. Work with Fortune 500 clients to transform legacy enterprise architectures, implement ERP solutions, and drive digital innovation.",
    responsibilities: [
      "Analyze client business workflows and formulate scalable technological roadmaps.",
      "Implement business intelligence, automated workflows, and data visualizations.",
      "Work with cross-functional technical teams to deliver end-to-end digital solutions.",
      "Conduct stakeholder presentations and prepare structured technical documentation.",
    ],
    packageLpa: 8.5,
    packageDetails: "₹8.5 LPA (Fixed: ₹7.6 LPA + Variable Performance: ₹0.9 LPA)",
    location: "Hyderabad / Bengaluru",
    workMode: "HYBRID",
    requiredSkills: ["Problem Solving", "SQL", "Python / Java", "Data Analysis", "Communication", "SDLC"],
    eligibility: {
      eligibleDepartments: ["all", "cse", "ece", "eee", "mech", "civil", "it"],
      eligibleYears: [4],
      minCgpa: 6.5,
      maxBacklogs: 1,
      graduationYear: "2025",
    },
    applicationDeadline: "2026-10-25T23:59:59Z",
    driveDate: "2026-11-02T09:00:00Z",
    selectionRounds: [
      "Online Cognitive Ability & Tech Aptitude Test",
      "Group Case Discussion & Problem Solving",
      "Technical & Techno-Managerial Interview",
      "Partner / Leadership Round",
    ],
    applicationMethod: "DIRECT",
    status: "PUBLISHED",
    applicantsCount: 110,
    createdBy: "user-admin-001",
    createdAt: "2026-09-04T12:00:00Z",
    updatedAt: "2026-09-04T12:00:00Z",
  },
  {
    id: "place-105",
    type: "PLACEMENT",
    companyName: "Texas Instruments",
    companyLogo: "/companies/ti.png",
    companyWebsite: "https://careers.ti.com",
    role: "Digital VLSI Design & Verification Engineer",
    domain: "VLSI & Semiconductors",
    description:
      "Join the analog and digital semiconductor design team at Texas Instruments. Responsible for RTL design, digital synthesis, static timing analysis (STA), and UVM testbench verification for ultra-low-power microcontrollers.",
    responsibilities: [
      "Author Verilog/SystemVerilog RTL code for digital logic blocks.",
      "Construct constrained-random verification testbenches using UVM methodologies.",
      "Run synthesis, formal verification, and static timing analysis constraints.",
      "Collaborate with physical design engineers on power, performance, and area (PPA) goals.",
    ],
    packageLpa: 19.2,
    packageDetails: "₹19.2 LPA (Base: ₹16.0 LPA + Performance Bonus: ₹2.2 LPA + Benefits: ₹1.0 LPA)",
    location: "Bengaluru, Karnataka",
    workMode: "ONSITE",
    requiredSkills: ["Verilog", "SystemVerilog", "UVM", "Digital Electronics", "STA", "Computer Architecture"],
    eligibility: {
      eligibleDepartments: ["ece", "eee"],
      eligibleYears: [4],
      minCgpa: 7.8,
      maxBacklogs: 0,
      graduationYear: "2025",
    },
    applicationDeadline: "2026-10-22T23:59:59Z",
    driveDate: "2026-10-30T09:00:00Z",
    selectionRounds: [
      "Digital Circuits & Verilog Online Assessment",
      "Technical Round 1: Logic Design & Timing Closure",
      "Technical Round 2: SystemVerilog / UVM Verification Concepts",
      "HR & Cultural Alignment Round",
    ],
    applicationMethod: "DIRECT",
    status: "PUBLISHED",
    applicantsCount: 19,
    createdBy: "user-admin-001",
    createdAt: "2026-09-05T14:00:00Z",
    updatedAt: "2026-09-05T14:00:00Z",
  },
  {
    id: "place-106",
    type: "PLACEMENT",
    companyName: "Amazon",
    companyLogo: "/companies/amazon.png",
    companyWebsite: "https://amazon.jobs",
    role: "Machine Learning Engineer (MLE-1)",
    domain: "AI/ML & Data Science",
    description:
      "Amazon Prime Video & Recommendation team in Hyderabad is hiring Machine Learning engineers. You will design, train, and deploy deep learning ranking models, graph neural networks, and vector retrieval pipelines at scale.",
    responsibilities: [
      "Build and maintain end-to-end ML inference pipelines using PyTorch, TensorFlow, and AWS SageMaker.",
      "Implement feature engineering and embeddings for personalized recommendation models.",
      "Monitor data drift, online A/B testing, and model latency metrics.",
      "Work with software engineers to integrate ML models into production services.",
    ],
    packageLpa: 28.5,
    packageDetails: "₹28.5 LPA (Base: ₹20 LPA + Sign-on: ₹4.5 LPA + RSUs: ₹4 LPA)",
    location: "Hyderabad, Telangana",
    workMode: "HYBRID",
    requiredSkills: ["Python", "PyTorch", "Machine Learning", "Data Structures", "Linear Algebra", "AWS"],
    eligibility: {
      eligibleDepartments: ["cse", "it"],
      eligibleYears: [4],
      minCgpa: 8.2,
      maxBacklogs: 0,
      graduationYear: "2025",
    },
    applicationDeadline: "2026-10-16T23:59:59Z",
    driveDate: "2026-10-24T09:00:00Z",
    selectionRounds: [
      "Online Assessment (DSA + ML Problem Solving)",
      "Technical Round 1: Algorithms & Coding",
      "Technical Round 2: Machine Learning System Design",
      "Amazon Leadership Principles & Behavioral Round",
    ],
    applicationMethod: "DIRECT",
    status: "PUBLISHED",
    applicantsCount: 34,
    createdBy: "user-admin-001",
    createdAt: "2026-09-06T10:00:00Z",
    updatedAt: "2026-09-06T10:00:00Z",
  },
  {
    id: "place-107",
    type: "PLACEMENT",
    companyName: "Cisco Systems",
    companyLogo: "/companies/cisco.png",
    companyWebsite: "https://www.cisco.com/c/en/us/about/careers.html",
    role: "Network Security & Systems Engineer",
    domain: "Cybersecurity & Networking",
    description:
      "Join Cisco's Enterprise Security & Routing engineering division. Design high-throughput packet inspection pipelines, zero-trust network protocols, and next-generation firewall software.",
    responsibilities: [
      "Develop network protocol stacks (TCP/IP, BGP, OSPF, TLS 1.3) in C/C++.",
      "Implement secure socket layers, cryptographic verification, and packet filtering engines.",
      "Automate network topology testing using Python and Wireshark.",
      "Analyze network latency bottlenecks and kernel packet processing.",
    ],
    packageLpa: 15.0,
    packageDetails: "₹15.0 LPA (Base: ₹13 LPA + Performance Incentive: ₹2 LPA)",
    location: "Bengaluru, Karnataka",
    workMode: "HYBRID",
    requiredSkills: ["C/C++", "Computer Networks", "TCP/IP", "Linux", "Socket Programming", "Python"],
    eligibility: {
      eligibleDepartments: ["cse", "it", "ece"],
      eligibleYears: [4],
      minCgpa: 7.0,
      maxBacklogs: 0,
      graduationYear: "2025",
    },
    applicationDeadline: "2026-10-26T23:59:59Z",
    driveDate: "2026-11-04T10:00:00Z",
    selectionRounds: [
      "Networking & Coding Assessment",
      "Technical Round 1: Computer Networks & C Programming",
      "Technical Round 2: OS, Threads, & Socket Design",
      "HR Interview",
    ],
    applicationMethod: "DIRECT",
    status: "PUBLISHED",
    applicantsCount: 39,
    createdBy: "user-admin-001",
    createdAt: "2026-09-07T11:00:00Z",
    updatedAt: "2026-09-07T11:00:00Z",
  },
  {
    id: "place-108",
    type: "PLACEMENT",
    companyName: "TCS Digital",
    companyLogo: "/companies/tcs.png",
    companyWebsite: "https://www.tcs.com/careers",
    role: "Full Stack Digital Engineer",
    domain: "Software Engineering",
    description:
      "TCS Digital hiring drive for 2025 graduating engineers. Opportunity to work on modern cloud-native architectures, enterprise React/Node.js web portals, and microservice backends.",
    responsibilities: [
      "Develop responsive user interfaces using React, Next.js, and Tailwind CSS.",
      "Build robust RESTful API endpoints using Node.js / Java Spring Boot.",
      "Integrate SQL and NoSQL database schemas with transactional consistency.",
      "Participate in automated software quality testing and DevOps deployment.",
    ],
    packageLpa: 7.5,
    packageDetails: "₹7.5 LPA (Fixed: ₹7.0 LPA + Milestone Incentives: ₹0.5 LPA)",
    location: "Hyderabad, Telangana",
    workMode: "HYBRID",
    requiredSkills: ["JavaScript", "React", "Java", "SQL", "HTML/CSS", "Git"],
    eligibility: {
      eligibleDepartments: ["all", "cse", "ece", "eee", "mech", "civil", "it"],
      eligibleYears: [4],
      minCgpa: 7.0,
      maxBacklogs: 1,
      graduationYear: "2025",
    },
    applicationDeadline: "2026-10-30T23:59:59Z",
    driveDate: "2026-11-08T09:00:00Z",
    selectionRounds: [
      "TCS NQT Advanced Digital Assessment (Coding + Advanced Aptitude)",
      "Technical Interview (Full Stack & DBMS)",
      "Managerial & HR Interview",
    ],
    applicationMethod: "DIRECT",
    status: "PUBLISHED",
    applicantsCount: 85,
    createdBy: "user-admin-001",
    createdAt: "2026-09-08T15:00:00Z",
    updatedAt: "2026-09-08T15:00:00Z",
  },
  {
    id: "place-109",
    type: "PLACEMENT",
    companyName: "Intel Corporation",
    companyLogo: "/companies/intel.png",
    companyWebsite: "https://www.intel.com/content/www/us/en/jobs/jobs-at-intel.html",
    role: "SOC Firmware & Pre-Silicon Verification Engineer",
    domain: "Semiconductors & Embedded",
    description:
      "Join Intel's Xeon and Core processor verification engineering group. Work with cross-functional teams verifying next-generation CPU micro-architectures, cache coherence protocols, and low-level power management firmware.",
    responsibilities: [
      "Develop SystemVerilog testbenches for pre-silicon processor simulation.",
      "Debug system crashes and cache snooping protocols in emulated environments.",
      "Write low-level assembly and C validation drivers for hardware IP blocks.",
      "Collaborate with architects on functional coverage analysis and bug triage.",
    ],
    packageLpa: 17.5,
    packageDetails: "₹17.5 LPA (Base: ₹14.5 LPA + Performance Bonus: ₹2.0 LPA + Relocation: ₹1.0 LPA)",
    location: "Bengaluru, Karnataka",
    workMode: "ONSITE",
    requiredSkills: ["SystemVerilog", "C++", "Computer Architecture", "Digital Design", "Perl/Python", "Linux"],
    eligibility: {
      eligibleDepartments: ["ece", "eee", "cse"],
      eligibleYears: [4],
      minCgpa: 7.5,
      maxBacklogs: 0,
      graduationYear: "2025",
    },
    applicationDeadline: "2026-10-28T23:59:59Z",
    driveDate: "2026-11-06T10:00:00Z",
    selectionRounds: [
      "Intel Pre-Screen Online Test (Architecture + Coding)",
      "Technical Round 1: Processor Architecture & Pipelining",
      "Technical Round 2: Verification Methodologies & C++",
      "Behavioral & HR Round",
    ],
    applicationMethod: "DIRECT",
    status: "PUBLISHED",
    applicantsCount: 22,
    createdBy: "user-admin-001",
    createdAt: "2026-09-09T09:00:00Z",
    updatedAt: "2026-09-09T09:00:00Z",
  },
  {
    id: "place-110",
    type: "PLACEMENT",
    companyName: "Salesforce",
    companyLogo: "/companies/salesforce.png",
    companyWebsite: "https://salesforce.com/careers",
    role: "Associate Member of Technical Staff (AMTS)",
    domain: "Software Engineering",
    description:
      "Build high-throughput multitenant enterprise cloud infrastructure. Develop distributed caching tiers, core query optimization engines, and resilient microservices for Salesforce Core Platform.",
    responsibilities: [
      "Write production-grade Java and TypeScript code for enterprise web services.",
      "Optimize relational and distributed database queries for sub-millisecond execution.",
      "Design fault-tolerant event processing pipelines using Apache Kafka.",
      "Conduct thorough code reviews and advocate for modern testing best practices.",
    ],
    packageLpa: 22.0,
    packageDetails: "₹22.0 LPA (Base: ₹17 LPA + Annual Bonus: ₹2.5 LPA + Stocks: ₹2.5 LPA)",
    location: "Hyderabad, Telangana",
    workMode: "HYBRID",
    requiredSkills: ["Java", "Data Structures", "Algorithms", "Kafka", "SQL", "Object-Oriented Design"],
    eligibility: {
      eligibleDepartments: ["cse", "it"],
      eligibleYears: [4],
      minCgpa: 8.0,
      maxBacklogs: 0,
      graduationYear: "2025",
    },
    applicationDeadline: "2026-10-19T23:59:59Z",
    driveDate: "2026-10-27T09:30:00Z",
    selectionRounds: [
      "HackerRank Online Assessment (3 Coding Questions)",
      "Technical Interview 1: Data Structures & OOP",
      "Technical Interview 2: High-Level System Architecture",
      "Culture & Values Interview",
    ],
    applicationMethod: "DIRECT",
    status: "PUBLISHED",
    applicantsCount: 48,
    createdBy: "user-admin-001",
    createdAt: "2026-09-10T11:00:00Z",
    updatedAt: "2026-09-10T11:00:00Z",
  },
];

// ─── Deterministic Seed Internships ──────────────────────────────────────────

export const SEED_INTERNSHIPS: InternshipOpportunity[] = [
  {
    id: "intern-201",
    type: "INTERNSHIP",
    companyName: "Microsoft",
    companyLogo: "/companies/microsoft.png",
    companyWebsite: "https://careers.microsoft.com",
    role: "Software Engineering Summer Intern 2025",
    domain: "Software Engineering",
    description:
      "2-month summer internship for 3rd-year engineering students. Work alongside full-time Microsoft engineers on Bing, Office 365, or Azure developer tooling.",
    responsibilities: [
      "Implement features in real-world Microsoft software repositories.",
      "Write clean, modular code with complete automated unit test coverage.",
      "Present project milestone progress to engineering leads and mentors.",
      "Participate in intern hackathons, tech talks, and leadership sessions.",
    ],
    stipendMonthly: 50000,
    stipendDetails: "₹50,000 / month + Travel Allowance + PPO Opportunity",
    durationMonths: 2,
    location: "Hyderabad, Telangana",
    workMode: "HYBRID",
    requiredSkills: ["Data Structures", "Algorithms", "C++ / Java / C#", "Problem Solving", "Git"],
    eligibility: {
      eligibleDepartments: ["cse", "it"],
      eligibleYears: [3],
      minCgpa: 7.5,
      maxBacklogs: 0,
      graduationYear: "2026",
    },
    applicationDeadline: "2026-10-15T23:59:59Z",
    startDate: "2027-05-15T09:00:00Z",
    applicationMethod: "DIRECT",
    status: "PUBLISHED",
    applicantsCount: 64,
    createdBy: "user-admin-001",
    createdAt: "2026-09-01T09:00:00Z",
    updatedAt: "2026-09-01T09:00:00Z",
  },
  {
    id: "intern-202",
    type: "INTERNSHIP",
    companyName: "Qualcomm",
    companyLogo: "/companies/qualcomm.png",
    companyWebsite: "https://www.qualcomm.com/careers",
    role: "Embedded Systems & 5G Modem Intern",
    domain: "Embedded Systems & Telecom",
    description:
      "3-month summer internship in Qualcomm's 5G physical layer simulation group. Work with DSP algorithms, RTOS board brings-ups, and wireless modem optimization.",
    responsibilities: [
      "Develop embedded C firmware test harnesses for Snapdragon modem subsystems.",
      "Simulate digital communication channel noise and error-correction codes in Python/MATLAB.",
      "Assist in hardware testing and signal integrity verification in wireless labs.",
    ],
    stipendMonthly: 45000,
    stipendDetails: "₹45,000 / month + Pre-Placement Interview (PPI) eligibility",
    durationMonths: 3,
    location: "Hyderabad, Telangana",
    workMode: "ONSITE",
    requiredSkills: ["C", "Digital Signal Processing", "Microcontrollers", "MATLAB", "Electronics"],
    eligibility: {
      eligibleDepartments: ["ece", "eee"],
      eligibleYears: [3],
      minCgpa: 7.5,
      maxBacklogs: 0,
      graduationYear: "2026",
    },
    applicationDeadline: "2026-10-20T23:59:59Z",
    startDate: "2027-05-10T09:00:00Z",
    applicationMethod: "DIRECT",
    status: "PUBLISHED",
    applicantsCount: 31,
    createdBy: "user-admin-001",
    createdAt: "2026-09-02T10:30:00Z",
    updatedAt: "2026-09-02T10:30:00Z",
  },
  {
    id: "intern-203",
    type: "INTERNSHIP",
    companyName: "Amazon",
    companyLogo: "/companies/amazon.png",
    companyWebsite: "https://amazon.jobs",
    role: "Software Development Engineer Intern",
    domain: "Software Engineering",
    description:
      "Work with Amazon Retail, Prime, or AWS engineering teams. Design and deploy customer-facing web services with high availability and fault tolerance.",
    responsibilities: [
      "Collaborate with senior SDEs to design backend service components in Java/TypeScript.",
      "Implement automated regression testing and build CI/CD deployment pipelines.",
      "Participate in architectural reviews and learn Amazon leadership principles.",
    ],
    stipendMonthly: 60000,
    stipendDetails: "₹60,000 / month + Relocation Support + PPO Opportunity",
    durationMonths: 3,
    location: "Hyderabad, Telangana",
    workMode: "HYBRID",
    requiredSkills: ["Data Structures", "Java", "Object-Oriented Design", "SQL", "Linux"],
    eligibility: {
      eligibleDepartments: ["cse", "it", "ece"],
      eligibleYears: [3],
      minCgpa: 7.8,
      maxBacklogs: 0,
      graduationYear: "2026",
    },
    applicationDeadline: "2026-10-18T23:59:59Z",
    startDate: "2027-05-20T09:00:00Z",
    applicationMethod: "DIRECT",
    status: "PUBLISHED",
    applicantsCount: 78,
    createdBy: "user-admin-001",
    createdAt: "2026-09-03T11:00:00Z",
    updatedAt: "2026-09-03T11:00:00Z",
  },
  {
    id: "intern-204",
    type: "INTERNSHIP",
    companyName: "Goldman Sachs",
    companyLogo: "/companies/goldman.png",
    companyWebsite: "https://www.goldmansachs.com/careers",
    role: "Summer Technology Analyst Intern",
    domain: "FinTech & Analytics",
    description:
      "Campus-wide 2-month summer analyst program open to all 3rd-year engineering departments. Work on high-frequency financial platforms, algorithmic risk engines, and enterprise data analytics.",
    responsibilities: [
      "Design quantitative analytical tools and financial data processing pipelines.",
      "Write performant Python/Java code for distributed trade validation systems.",
      "Collaborate with global technical teams across New York, London, and Bengaluru.",
    ],
    stipendMonthly: 75000,
    stipendDetails: "₹75,000 / month + Full PPO Conversion Track",
    durationMonths: 2,
    location: "Bengaluru, Karnataka",
    workMode: "HYBRID",
    requiredSkills: ["Data Structures", "Python / C++ / Java", "SQL", "Problem Solving", "Analytical Thinking"],
    eligibility: {
      eligibleDepartments: ["all", "cse", "ece", "eee", "mech", "civil", "it"],
      eligibleYears: [3],
      minCgpa: 7.5,
      maxBacklogs: 0,
      graduationYear: "2026",
    },
    applicationDeadline: "2026-10-22T23:59:59Z",
    startDate: "2027-05-15T09:00:00Z",
    applicationMethod: "DIRECT",
    status: "PUBLISHED",
    applicantsCount: 92,
    createdBy: "user-admin-001",
    createdAt: "2026-09-04T13:00:00Z",
    updatedAt: "2026-09-04T13:00:00Z",
  },
  {
    id: "intern-205",
    type: "INTERNSHIP",
    companyName: "NVIDIA",
    companyLogo: "/companies/nvidia.png",
    companyWebsite: "https://www.nvidia.com/en-us/about-nvidia/careers",
    role: "GPU & Deep Learning Software Intern",
    domain: "AI/ML & GPU Computing",
    description:
      "Join NVIDIA's CUDA and AI software optimization group in Pune. Work on TensorRT acceleration libraries, CUDA kernel profiling, and deep learning model quantization.",
    responsibilities: [
      "Write and optimize CUDA C/C++ kernels for matrix operations on modern GPU architectures.",
      "Benchmark transformer inference latency using TensorRT and PyTorch.",
      "Analyze memory throughput, warp divergence, and register pressure.",
    ],
    stipendMonthly: 65000,
    stipendDetails: "₹65,000 / month + Housing Stipend",
    durationMonths: 3,
    location: "Pune, Maharashtra",
    workMode: "ONSITE",
    requiredSkills: ["C++", "CUDA", "GPU Architecture", "PyTorch", "Parallel Programming"],
    eligibility: {
      eligibleDepartments: ["cse", "ece"],
      eligibleYears: [3],
      minCgpa: 8.0,
      maxBacklogs: 0,
      graduationYear: "2026",
    },
    applicationDeadline: "2026-10-25T23:59:59Z",
    startDate: "2027-05-10T09:00:00Z",
    applicationMethod: "DIRECT",
    status: "PUBLISHED",
    applicantsCount: 38,
    createdBy: "user-admin-001",
    createdAt: "2026-09-05T14:30:00Z",
    updatedAt: "2026-09-05T14:30:00Z",
  },
  {
    id: "intern-206",
    type: "INTERNSHIP",
    companyName: "Bosch",
    companyLogo: "/companies/bosch.png",
    companyWebsite: "https://www.bosch.in/careers",
    role: "IoT & Connected Mobility Engineering Intern",
    domain: "IoT & Automotive",
    description:
      "Open to ECE, EEE, CSE, and MECH 3rd-year students. Develop connected vehicle telemetry, sensor fusion algorithms, and edge IoT firmware for next-generation smart mobility.",
    responsibilities: [
      "Develop MQTT/CoAP telemetry communication protocols on embedded hardware.",
      "Integrate sensor data feeds (IMU, GPS, CAN bus) into cloud dashboard portals.",
      "Validate automotive safety standards and participate in lab bench testing.",
    ],
    stipendMonthly: 35000,
    stipendDetails: "₹35,000 / month + Certificate & Pre-Placement Interview",
    durationMonths: 4,
    location: "Bengaluru, Karnataka",
    workMode: "ONSITE",
    requiredSkills: ["C/C++", "Python", "IoT Protocols", "Microcontrollers", "Basic Electronics"],
    eligibility: {
      eligibleDepartments: ["all", "ece", "eee", "cse", "mech", "it"],
      eligibleYears: [3],
      minCgpa: 7.0,
      maxBacklogs: 1,
      graduationYear: "2026",
    },
    applicationDeadline: "2026-10-28T23:59:59Z",
    startDate: "2027-05-01T09:00:00Z",
    applicationMethod: "DIRECT",
    status: "PUBLISHED",
    applicantsCount: 45,
    createdBy: "user-admin-001",
    createdAt: "2026-09-06T15:00:00Z",
    updatedAt: "2026-09-06T15:00:00Z",
  },
  {
    id: "intern-207",
    type: "INTERNSHIP",
    companyName: "Adobe",
    companyLogo: "/companies/adobe.png",
    companyWebsite: "https://www.adobe.com/careers.html",
    role: "Product Engineering Intern",
    domain: "Software Engineering",
    description:
      "Join Adobe Creative Cloud or Document Cloud product engineering teams. Develop web and desktop experiences, WebAssembly modules, and generative AI creative tools.",
    responsibilities: [
      "Build fluid canvas UI components using React, TypeScript, and WebGL.",
      "Optimize rendering pipelines and client-side performance.",
      "Collaborate with UX designers and senior engineers on creative feature sets.",
    ],
    stipendMonthly: 70000,
    stipendDetails: "₹70,000 / month + Equipment + PPO Opportunities",
    durationMonths: 2,
    location: "Noida / Bengaluru",
    workMode: "HYBRID",
    requiredSkills: ["JavaScript", "TypeScript", "React", "Data Structures", "Web Standards"],
    eligibility: {
      eligibleDepartments: ["cse", "it"],
      eligibleYears: [3],
      minCgpa: 7.8,
      maxBacklogs: 0,
      graduationYear: "2026",
    },
    applicationDeadline: "2026-10-17T23:59:59Z",
    startDate: "2027-05-15T09:00:00Z",
    applicationMethod: "DIRECT",
    status: "PUBLISHED",
    applicantsCount: 52,
    createdBy: "user-admin-001",
    createdAt: "2026-09-07T12:00:00Z",
    updatedAt: "2026-09-07T12:00:00Z",
  },
  {
    id: "intern-208",
    type: "INTERNSHIP",
    companyName: "Analog Devices",
    companyLogo: "/companies/analog.png",
    companyWebsite: "https://careers.analog.com",
    role: "Analog & Mixed-Signal Circuit Design Intern",
    domain: "VLSI & Semiconductors",
    description:
      "Join Analog Devices India engineering center. Work on precision operational amplifiers, ADC/DAC data converters, and SPICE analog circuit simulations.",
    responsibilities: [
      "Perform schematic entry and SPICE circuit simulation for analog blocks.",
      "Analyze circuit noise, bandwidth, power dissipation, and PVT corners.",
      "Document test results and collaborate with silicon layout engineers.",
    ],
    stipendMonthly: 40000,
    stipendDetails: "₹40,000 / month + Lab Mentorship",
    durationMonths: 3,
    location: "Bengaluru, Karnataka",
    workMode: "ONSITE",
    requiredSkills: ["Analog Circuit Design", "SPICE Simulation", "Op-Amps", "Signals & Systems", "Semiconductor Physics"],
    eligibility: {
      eligibleDepartments: ["ece", "eee"],
      eligibleYears: [3],
      minCgpa: 7.5,
      maxBacklogs: 0,
      graduationYear: "2026",
    },
    applicationDeadline: "2026-10-24T23:59:59Z",
    startDate: "2027-05-10T09:00:00Z",
    applicationMethod: "DIRECT",
    status: "PUBLISHED",
    applicantsCount: 20,
    createdBy: "user-admin-001",
    createdAt: "2026-09-08T10:00:00Z",
    updatedAt: "2026-09-08T10:00:00Z",
  },
];

// ─── Default Mock Student Profile ────────────────────────────────────────────

export const DEFAULT_STUDENT_PROFILES: Record<string, StudentCareerProfile> = {
  "user-std-101": {
    studentId: "user-std-101",
    studentName: "K. Rohit Reddy",
    department: "Computer Science & Engineering",
    currentYear: 4, // 4th year for testing placement applications
    cgpa: 8.4,
    backlogsCount: 0,
    skills: ["Java", "Python", "Data Structures", "Algorithms", "React", "SQL", "Git", "System Design"],
    resumeTitle: "Rohit_Reddy_SDE_Resume_2025.pdf",
    preferredDomains: ["Software Engineering", "AI/ML", "Cloud"],
    graduationYear: "2025",
  },
  "user-mod-001": {
    studentId: "user-mod-001",
    studentName: "Priya Sharma (Moderator)",
    department: "Electronics & Communication Engineering",
    currentYear: 3, // 3rd year for testing internship applications
    cgpa: 8.2,
    backlogsCount: 0,
    skills: ["Embedded C", "C++", "Microcontrollers", "Verilog", "Python", "MATLAB"],
    resumeTitle: "Priya_Sharma_Hardware_Resume.pdf",
    preferredDomains: ["Embedded Systems", "VLSI"],
    graduationYear: "2026",
  },
};

// ─── Seed Resume Reviews ─────────────────────────────────────────────────────

export const SEED_RESUME_REVIEWS: ResumeReviewRequest[] = [
  {
    id: "rev-req-101",
    studentId: "user-std-101",
    studentName: "K. Rohit Reddy",
    studentEmail: "student@mlrit.ac.in",
    studentDepartment: "Computer Science & Engineering",
    targetRole: "Software Development Engineer (SDE-1)",
    targetCompany: "Google / Amazon",
    resumeTitle: "Rohit_Reddy_Software_2025.pdf",
    resumeFileName: "Rohit_Reddy_Software_2025.pdf",
    notes: "Focusing on backend systems, DSA projects, and cloud microservices. Please review impact metrics.",
    status: "REVIEWED",
    feedback: {
      id: "fb-101",
      reviewerName: "Senior Career Coordinator",
      overallScore: 88,
      sectionScores: {
        formatting: 92,
        content: 85,
        skillsImpact: 90,
        brevity: 85,
      },
      strengths: [
        "Strong action verbs and clear XYZ formula metrics in project descriptions (e.g. 'reduced latency by 35%').",
        "Well-structured technical skills section categorized into Languages, Frameworks, and Tools.",
        "Consistent single-page typography with clean margins and ATS-friendly headers.",
      ],
      weaknesses: [
        "Coursework section takes up too much vertical space; consolidate into 2 lines.",
        "Include GitHub or live deployment links for your 2 top projects.",
      ],
      recommendations: [
        "Highlight your experience with Docker and unit testing under the CampusNexus project.",
        "Add a brief bullet point on concurrency/threading optimization under your Java backend service.",
      ],
      reviewedAt: "2026-09-08T14:30:00Z",
    },
    createdAt: "2026-09-06T10:00:00Z",
    updatedAt: "2026-09-08T14:30:00Z",
  },
];

// ─── Seed Smart Collections ──────────────────────────────────────────────────

export const SEED_COLLECTIONS: SmartCollection[] = [
  {
    id: "col-101",
    studentId: "user-std-101",
    name: "Target Tier-1 Companies",
    description: "Dream companies with competitive SDE openings for 2025 campus season.",
    color: "#6366f1",
    items: [
      {
        id: "item-101",
        opportunityId: "place-101",
        opportunityType: "PLACEMENT",
        companyName: "Google",
        role: "Software Development Engineer (SDE-1)",
        location: "Hyderabad, Telangana",
        compensationDisplay: "₹24.0 LPA",
        addedAt: "2026-09-08T11:00:00Z",
        note: "Review graph algorithms and distributed systems beforehand.",
      },
      {
        id: "item-102",
        opportunityId: "place-103",
        opportunityType: "PLACEMENT",
        companyName: "Microsoft",
        role: "Cloud & AI Solutions Engineer",
        location: "Hyderabad, Telangana",
        compensationDisplay: "₹21.5 LPA",
        addedAt: "2026-09-09T09:30:00Z",
      },
    ],
    createdAt: "2026-09-08T10:30:00Z",
    updatedAt: "2026-09-09T09:30:00Z",
  },
];
